// Generated by Cursor
import SwiftUI
{% if cookiecutter.include_persistence == 'yes' %}
import SwiftData
{% endif %}

@main
struct {{cookiecutter.project_name}}App: App {
    {% if cookiecutter.include_persistence == 'yes' %}
    private let modelContainer: ModelContainer
    
    init() {
        do {
            {% if cookiecutter.include_icloud == 'yes' %}
            let schema = Schema([
                // Add your @Model types here
            ])
            let config = ModelConfiguration(
                cloudKitDatabase: .automatic
            )
            modelContainer = try ModelContainer(for: schema, configurations: [config])
            {% else %}
            modelContainer = try ModelContainer(for: Schema([
                // Add your @Model types here
            ]))
            {% endif %}
        } catch {
            fatalError("Failed to initialize ModelContainer: \(error)")
        }
    }
    {% endif %}
    
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
        {% if cookiecutter.include_persistence == 'yes' %}
        .modelContainer(modelContainer)
        {% endif %}
        #if os(macOS)
        .windowStyle(.hiddenTitleBar)
        .defaultSize(width: 900, height: 600)
        #endif
    }
}
