#!/usr/bin/env python3
# Generated by Cursor
"""
交互式 CLI 工具，用于从 cookiecutter 模板创建 Python 项目。

用法:
    python create_project.py                    # 交互模式
    python create_project.py --name my-app      # 带参数模式
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path
from typing import Optional, Union

try:
    import questionary
    from questionary import Style
    from rich.console import Console
    from rich.panel import Panel
    from rich.text import Text
    from cookiecutter.main import cookiecutter
except ImportError:
    print("缺少依赖。请执行: pip install -r requirements.txt")
    sys.exit(1)


console = Console()

# 自定义 questionary 样式：高亮背景显示选中项
CUSTOM_STYLE = Style([
    ("qmark", "fg:cyan bold"),             # 问号
    ("question", "bold"),                  # 问题文本
    ("answer", "fg:cyan bold"),            # 已回答的值
    ("pointer", "fg:black bg:cyan bold"),  # 指针（与高亮一致）
    ("highlighted", "fg:black bg:cyan"),   # 高亮选中项
    ("selected", "fg:cyan"),               # 已选择的复选框项
    ("text", ""),                          # 普通文本
    ("instruction", "fg:gray"),            # 指令提示
])

# 模板目录 (cli 文件夹的父目录)
TEMPLATE_DIR = Path(__file__).parent.parent.absolute()


def print_banner() -> None:
    """打印欢迎横幅。"""
    banner = Text()
    banner.append("Python 项目生成器\n", style="bold cyan")
    banner.append("FastAPI / React / LangChain 模板\n", style="dim")
    banner.append("可配置的 Python 应用模板", style="dim italic")
    console.print(Panel(banner, border_style="cyan"))


def select_folder_with_finder() -> Optional[str]:
    """使用 Finder 选择文件夹 (仅 macOS)。"""
    try:
        script = '''
        tell application "Finder"
            activate
        end tell
        set selectedFolder to choose folder with prompt "选择项目输出目录"
        return POSIX path of selectedFolder
        '''
        result = subprocess.run(
            ["osascript", "-e", script],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            return result.stdout.strip()
        return None
    except Exception:
        return None


def validate_project_name(name: str) -> Union[bool, str]:
    """验证项目名称 (kebab-case)。"""
    if not name:
        return "项目名称不能为空"
    if not name[0].isalpha():
        return "项目名称必须以字母开头"
    if not all(c.isalnum() or c == "-" for c in name):
        return "项目名称只能包含字母、数字和连字符 (kebab-case)"
    if name != name.lower():
        return "项目名称必须小写"
    return True


def interactive_prompt() -> tuple:
    """运行交互式提示，收集项目配置。返回 (config_dict, output_dir)。"""
    console.print("\n[bold]项目配置[/bold]\n")

    # 项目名称
    project_name = questionary.text(
        "项目名称 (kebab-case):",
        default="my-python-app",
        validate=validate_project_name,
    ).ask()
    if not project_name:
        sys.exit(0)

    # 项目描述
    description = questionary.text(
        "项目描述:",
        default="A Python application",
    ).ask()
    if not description:
        sys.exit(0)

    # 作者名称
    author_name = questionary.text(
        "作者/组织名称:",
        default="Developer",
    ).ask()
    if not author_name:
        sys.exit(0)

    console.print("\n[bold]可选模块[/bold]\n")

    # FastAPI
    use_fastapi = questionary.confirm(
        "包含 FastAPI?",
        default=True,
    ).ask()
    if use_fastapi is None:
        sys.exit(0)

    # React 前端
    use_react = questionary.confirm(
        "包含 React 前端?",
        default=False,
    ).ask()
    if use_react is None:
        sys.exit(0)

    # LangChain
    use_langchain = questionary.confirm(
        "包含 LangChain (LLM 支持)?",
        default=False,
    ).ask()
    if use_langchain is None:
        sys.exit(0)

    # 项目结构（第一项为默认）
    project_structure = questionary.select(
        "项目结构:",
        choices=[
            questionary.Choice("扁平结构 (flat)", value="flat"),
            questionary.Choice("分层架构 (layered)", value="layered"),
        ],
        style=CUSTOM_STYLE,
    ).ask()
    if not project_structure:
        sys.exit(0)

    # Python 版本（system 在前作为默认）
    python_version = questionary.select(
        "Python 版本:",
        choices=[
            questionary.Choice("系统最新版本 (system)", value="system"),
            questionary.Choice("Python 3.8", value="3.8"),
        ],
        style=CUSTOM_STYLE,
    ).ask()
    if not python_version:
        sys.exit(0)

    console.print("\n[bold]输出位置[/bold]\n")

    # 输出目录选择（当前目录在前作为默认）
    output_dir = None
    output_choice = questionary.select(
        "项目输出目录:",
        choices=[
            questionary.Choice(f"当前目录 ({os.getcwd()})", value="cwd"),
            questionary.Choice("通过 Finder 选择...", value="finder"),
            questionary.Choice("手动输入路径", value="manual"),
        ],
        style=CUSTOM_STYLE,
    ).ask()
    if not output_choice:
        sys.exit(0)

    if output_choice == "finder":
        console.print("[dim]正在打开 Finder...[/dim]")
        output_dir = select_folder_with_finder()
        if output_dir:
            console.print(f"[green]已选择:[/green] {output_dir}")
        else:
            console.print("[yellow]未选择目录，使用当前目录[/yellow]")
            output_dir = os.getcwd()
    elif output_choice == "manual":
        output_dir = questionary.path(
            "输入目录路径:",
            default=os.getcwd(),
            only_directories=True,
        ).ask()
        if not output_dir:
            output_dir = os.getcwd()
    else:
        output_dir = os.getcwd()

    config = {
        "project_name": project_name,
        "description": description,
        "author_name": author_name,
        "use_fastapi": "yes" if use_fastapi else "no",
        "use_react": "yes" if use_react else "no",
        "use_langchain": "yes" if use_langchain else "no",
        "project_structure": project_structure,
        "python_version": python_version,
    }

    return config, output_dir


def create_project(
    output_dir: Optional[str] = None,
    extra_context: Optional[dict] = None,
    no_input: bool = False,
) -> str:
    """从模板创建项目。"""
    output_dir = output_dir or os.getcwd()

    result = cookiecutter(
        str(TEMPLATE_DIR),
        output_dir=output_dir,
        extra_context=extra_context,
        no_input=no_input,
    )

    return result


def main() -> None:
    """主入口。"""
    parser = argparse.ArgumentParser(
        description="从模板创建 Python 项目"
    )
    parser.add_argument(
        "--name",
        "-n",
        help="项目名称 (kebab-case)",
    )
    parser.add_argument(
        "--description",
        "-d",
        help="项目描述",
    )
    parser.add_argument(
        "--author",
        "-a",
        help="作者/组织名称",
    )
    parser.add_argument(
        "--output-dir",
        "-o",
        help="输出目录 (默认: 当前目录)",
    )
    parser.add_argument(
        "--no-fastapi",
        action="store_true",
        help="排除 FastAPI",
    )
    parser.add_argument(
        "--react",
        action="store_true",
        help="包含 React 前端",
    )
    parser.add_argument(
        "--langchain",
        action="store_true",
        help="包含 LangChain",
    )
    parser.add_argument(
        "--structure",
        choices=["flat", "layered"],
        default="flat",
        help="项目结构 (默认: flat)",
    )
    parser.add_argument(
        "--python-version",
        choices=["3.8", "system"],
        default="system",
        help="Python 版本 (默认: system)",
    )
    parser.add_argument(
        "--non-interactive",
        action="store_true",
        help="非交互模式运行 (需要 --name)",
    )

    args = parser.parse_args()

    print_banner()

    if args.non_interactive:
        if not args.name:
            console.print("[red]错误: 非交互模式需要 --name 参数[/red]")
            sys.exit(1)

        extra_context = {
            "project_name": args.name,
            "description": args.description or "A Python application",
            "author_name": args.author or "Developer",
            "use_fastapi": "no" if args.no_fastapi else "yes",
            "use_react": "yes" if args.react else "no",
            "use_langchain": "yes" if args.langchain else "no",
            "project_structure": args.structure,
            "python_version": args.python_version,
        }
        output_dir = args.output_dir
    else:
        extra_context, output_dir = interactive_prompt()
        # 命令行参数优先级高于交互式选择
        if args.output_dir:
            output_dir = args.output_dir

    console.print("\n[bold]正在生成项目...[/bold]\n")

    # 预计的项目路径，用于失败时清理
    output_dir = output_dir or os.getcwd()
    expected_path = os.path.join(output_dir, extra_context["project_name"])

    try:
        project_path = create_project(
            output_dir=output_dir,
            extra_context=extra_context,
            no_input=True,
        )
        console.print(f"\n[green]项目创建成功:[/green] {project_path}")
    except Exception as e:
        import shutil
        import traceback
        console.print(f"\n[red]创建项目失败:[/red] {e}")
        console.print("\n[dim]堆栈跟踪:[/dim]")
        console.print(traceback.format_exc())
        # 清理失败的项目目录
        if os.path.exists(expected_path):
            shutil.rmtree(expected_path)
            console.print(f"\n[yellow]已清理:[/yellow] {expected_path}")
        sys.exit(1)


if __name__ == "__main__":
    main()
