// Generated by Cursor
// {{cookiecutter.package_name}} - SwiftUI Preview Tests (XCTest)

#if canImport(SwiftUI) && canImport(XCTest)
import XCTest
import SwiftUI
@testable import {{cookiecutter.package_name}}

@available(iOS 17.0, macOS 14.0, *)
final class ExampleViewTests: XCTestCase {
    
    func testExampleViewInitialization() {
        let view = ExampleView()
        XCTAssertNotNil(view)
    }
    
    func testExampleViewWithCustomTitle() {
        let customTitle = "Custom Title"
        let view = ExampleView(title: customTitle)
        XCTAssertNotNil(view)
    }
    
    func testExampleViewSnapshot() throws {
        let view = ExampleView(title: "Test")
        
        // Create a hosting controller for snapshot testing
        #if os(iOS)
        let hostingController = UIHostingController(rootView: view)
        hostingController.view.frame = CGRect(x: 0, y: 0, width: 375, height: 200)
        hostingController.view.layoutIfNeeded()
        
        XCTAssertNotNil(hostingController.view)
        XCTAssertEqual(hostingController.view.frame.width, 375)
        #elseif os(macOS)
        let hostingView = NSHostingView(rootView: view)
        hostingView.frame = NSRect(x: 0, y: 0, width: 375, height: 200)
        
        XCTAssertNotNil(hostingView)
        XCTAssertEqual(hostingView.frame.width, 375)
        #endif
    }
    
    func testExampleViewRendersCycle() throws {
        let view = ExampleView()
        
        #if os(iOS)
        let hostingController = UIHostingController(rootView: view)
        
        // Trigger view lifecycle
        hostingController.loadViewIfNeeded()
        XCTAssertNotNil(hostingController.view)
        
        // Force layout pass
        hostingController.view.setNeedsLayout()
        hostingController.view.layoutIfNeeded()
        #elseif os(macOS)
        let hostingView = NSHostingView(rootView: view)
        hostingView.layout()
        XCTAssertNotNil(hostingView)
        #endif
    }
}

// MARK: - ViewInspector Style Testing (Optional Extension Point)

@available(iOS 17.0, macOS 14.0, *)
extension ExampleViewTests {
    
    /// Test that view hierarchy can be created without crashes
    func testViewHierarchyStability() {
        let views = (0..<100).map { ExampleView(title: "View \($0)") }
        XCTAssertEqual(views.count, 100)
    }
    
    /// Test view with various title lengths
    func testViewWithVariousTitleLengths() {
        let titles = [
            "",
            "A",
            "Short",
            "A medium length title for testing",
            String(repeating: "Long ", count: 50)
        ]
        
        for title in titles {
            let view = ExampleView(title: title)
            XCTAssertNotNil(view, "View should handle title: \(title.prefix(20))...")
        }
    }
}
#endif

