// Generated by Cursor
// {{cookiecutter.package_name}} - Unit Tests (Swift Testing)

import Testing
@testable import {{cookiecutter.package_name}}

@Suite("{{cookiecutter.package_name}} Tests")
struct {{cookiecutter.package_name}}Tests {
    
    @Test("Library version is set")
    func versionIsSet() {
        #expect({{cookiecutter.package_name}}.version == "1.0.0")
    }
}

@Suite("ExampleService Tests")
struct ExampleServiceTests {
    let service = ExampleService()
    
    @Test("Greet returns correct message")
    func greetReturnsCorrectMessage() {
        let result = service.greet("Swift")
        #expect(result == "Hello, Swift!")
    }
    
    @Test("Greet with empty name")
    func greetWithEmptyName() {
        let result = service.greet("")
        #expect(result == "Hello, !")
    }
    
    @Test("Add returns correct sum")
    func addReturnsCorrectSum() {
        #expect(service.add(2, 3) == 5)
        #expect(service.add(-1, 1) == 0)
        #expect(service.add(0, 0) == 0)
    }
    
    @Test("Add with negative numbers", arguments: [
        (-5, -3, -8),
        (-10, 5, -5),
        (100, -100, 0)
    ])
    func addWithNegativeNumbers(a: Int, b: Int, expected: Int) {
        #expect(service.add(a, b) == expected)
    }
}

