// Generated by Cursor
//! {{ cookiecutter.project_description }}

use tauri::Manager;

{% raw %}#[tauri::command]{% endraw %}
fn greet(name: &str) -> String {
    format!("Hello, {}! From Rust with ❤️", name)
}

{% raw %}#[cfg_attr(mobile, tauri::mobile_entry_point)]{% endraw %}
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .setup(|app| {
            {% raw %}#[cfg(debug_assertions)]{% endraw %}
            {
                let window = app.get_webview_window("main").unwrap();
                window.open_devtools();
            }
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

