// Generated by Cursor
/**
 * 全局应用状态管理 - Svelte 5 Runes
 */

/** 应用主题 */
export type Theme = "light" | "dark" | "system";

/** 应用状态 */
class AppState {
  theme = $state<Theme>("system");
  isLoading = $state(false);
  error = $state<string | null>(null);

  /** 计算属性：实际主题 */
  get effectiveTheme(): "light" | "dark" {
    if (this.theme === "system") {
      return window.matchMedia("(prefers-color-scheme: dark)").matches
        ? "dark"
        : "light";
    }
    return this.theme;
  }

  setTheme(theme: Theme) {
    this.theme = theme;
    document.documentElement.dataset.theme = this.effectiveTheme;
  }

  setLoading(loading: boolean) {
    this.isLoading = loading;
  }

  setError(error: string | null) {
    this.error = error;
  }

  clearError() {
    this.error = null;
  }
}

export const appState = new AppState();

