"""Generated by Cursor"""
{%- if cookiecutter.use_fastapi == "yes" %}
import json
from datetime import datetime
from typing import Dict, Any, Optional, Literal, TypeVar, List

from pydantic import BaseModel, Field

T = TypeVar('T')

SSEChunk = str


class StageInfo(BaseModel):
    """
    处理阶段信息模型
    
    用于描述处理流程中的某一阶段状态
    """
    stage: str  # 处理阶段标识
    stage_name: str  # 阶段名称
    stage_progress: int = Field(0, ge=0, le=100)  # 阶段进度(0-100)
    message: str  # 阶段消息
    pipeline: Optional[List[Any]] = None  # 可选的管道所有节点信息列表

    class Config:
        """模型配置"""
        json_schema_extra = {
            "example": {
                "stage": "preprocessing",
                "stage_name": "数据预处理",
                "stage_progress": 75,
                "message": "正在规范化数据格式"
            }
        }


class LogInfo(BaseModel):
    """日志信息模型"""
    time: str  # 时间戳
    type: Literal["info", "warning", "error"]  # 日志类型
    message: str  # 日志消息


class ExtraInfo(BaseModel):
    """额外信息模型"""
    stage_info: Optional[StageInfo] = None


class SSEJsonResponse(BaseModel):
    """SSE JSON响应模型"""
    status: Literal["started", "progress", "success", "error", "prepare"]
    percent: Optional[int] = None
    log: LogInfo
    is_end: bool = False
    result: Optional[Any] = None
    stage_info: Optional[StageInfo] = None


class SSEMessage(BaseModel):
    """
    SSE进度信息模型
    
    用于标准化SSE消息的格式和结构，确保前后端数据交互的一致性
    """
    status: Literal["started", "progress", "success", "error", "prepare"]
    log_type: Literal["info", "warning", "error"] = "info"
    message: str
    percent: Optional[int] = None
    result: Optional[Any] = None  # 用于存储最终结果或阶段性结果数据

    # 其他字段
    is_end: bool = False
    extra_info: Optional[ExtraInfo] = None

    @classmethod
    def create(cls,
        status: Literal["started", "progress", "success", "error", "prepare"],
        message: str,
        log_type: Literal["info", "warning", "error"] = "info",
        percent: Optional[int] = None,
        is_end: bool = False,
        result: Optional[Any] = None
    ) -> "SSEMessage":
        """创建普通SSE进度信息（不包含阶段信息）"""
        return cls(
            status=status,
            message=message,
            log_type=log_type,
            percent=percent,
            is_end=is_end,
            result=result
        )

    @classmethod
    def create_error(cls, message: str, is_end: bool = True) -> "SSEMessage":
        """快速创建错误类型的SSE进度信息"""
        return cls(
            status="error",
            message=message,
            log_type="error",
            is_end=is_end
        )
    
    @classmethod
    def create_with_stage(
        cls,
        status: Literal["started", "progress", "success", "error", "prepare"],
        message: str,
        stage_info: StageInfo,
        log_type: Literal["info", "warning", "error"] = "info",
        percent: Optional[int] = None,
        is_end: bool = False,
        result: Optional[Any] = None
    ) -> "SSEMessage":
        """
        创建带有阶段信息的SSE进度信息
        
        Args:
            status: 消息状态
            message: 消息文本
            stage_info: 阶段信息
            log_type: 日志类型
            percent: 总体进度百分比
            is_end: 是否为最后一条消息
            result: 可选的结果数据
            
        Returns:
            SSEMessage: 包含阶段信息的进度信息对象
        """
        return cls(
            status=status,
            message=message,
            log_type=log_type,
            percent=percent,
            is_end=is_end,
            result=result,
            extra_info=ExtraInfo(stage_info=stage_info)
        )
    
    def get_stage_info(self) -> Optional[StageInfo]:
        """获取阶段信息"""
        if self.extra_info and self.extra_info.stage_info:
            return self.extra_info.stage_info
        return None

    def to_json(self) -> Dict[str, Any]:
        """
        将SSE进度信息转换为JSON格式
        
        Returns:
            Dict[str, Any]: 包含所有SSE进度信息的JSON字典
        """
        log_info = LogInfo(
            time=datetime.now().strftime("%H:%M:%S"),
            type=self.log_type,
            message=self.message
        )
        
        json_response = SSEJsonResponse(
            status=self.status,
            percent=self.percent,
            log=log_info,
            is_end=self.is_end,
            result=self.result,
            stage_info=self.extra_info.stage_info if self.extra_info else None
        )
        
        return json_response.model_dump(exclude_none=True)

    def to_sse_chunk(self) -> SSEChunk:
        """
        将SSE进度信息转换为SSE消息块格式
        
        将模型数据转换为符合SSE协议的文本块，可直接发送给客户端
        
        Returns:
            str: 格式化的SSE消息字符串，格式为 "data: {json数据}\n\n"
        """
        # Generated by Cursor
        # 转换为SSE格式的消息块
        return f"data: {json.dumps(self.to_json())}\n\n"


def create_stage_progress(
    stage: str,
    stage_name: str,
    stage_progress: int,
    message: str,
    overall_percent: int,
    status: Literal["started", "progress", "success", "error", "prepare"] = "progress",
    log_type: Literal["info", "warning", "error"] = "info",
    is_end: bool = False,
    result: Optional[Any] = None,
    pipeline: Optional[List[Any]] = None
) -> SSEMessage:
    """
    创建带有阶段进度信息的SSE进度响应
    
    Args:
        stage: 处理阶段标识
        stage_name: 阶段名称
        stage_progress: 阶段进度(0-100)
        message: 阶段消息
        overall_percent: 总体进度百分比
        status: 消息状态
        log_type: 日志类型
        is_end: 是否为最后一条消息
        result: 可选的结果数据
        pipeline: 可选的管道所有节点信息列表
        
    Returns:
        SSEMessage: 包含阶段信息的进度信息对象
    """
    stage_info = StageInfo(
        stage=stage,
        stage_name=stage_name,
        stage_progress=stage_progress,
        message=message,
        pipeline=pipeline
    )

    return SSEMessage(
        status=status,
        message=message,
        log_type=log_type,
        percent=overall_percent,
        is_end=is_end,
        result=result,
        extra_info=ExtraInfo(stage_info=stage_info)
    )
{%- else %}
# sse_message.py 仅在 use_fastapi=yes 时使用
# 如果未启用 FastAPI，此文件将在后处理钩子中被删除
pass
{%- endif %}
