#!/usr/bin/env python3
# Generated by Cursor
"""
Cookiecutter 模板后处理钩子。
根据用户选项删除不需要的模块和配置。
"""

import base64
import json
import os
import shutil
import struct
import zlib

PROJECT_DIR = os.path.realpath(os.path.curdir)
# Jinja2 会渲染钩子文件，用变量避免特殊字符被解析
HASH = chr(35)  # '#'
LBRACE = chr(123)  # '{'
RBRACE = chr(125)  # '}'
PROJECT_NAME = "{{ cookiecutter.project_name }}"

# 配置标志
INCLUDE_TAILWIND = "{{ cookiecutter.include_tailwind }}" == "yes"
INCLUDE_I18N = "{{ cookiecutter.include_i18n }}" == "yes"
INCLUDE_TRAY = "{{ cookiecutter.include_tray }}" == "yes"
INCLUDE_UPDATER = "{{ cookiecutter.include_updater }}" == "yes"
INCLUDE_FS = "{{ cookiecutter.include_fs }}" == "yes"
INCLUDE_PYTHON = "{{ cookiecutter.include_python }}" == "yes"
PYTHON_INTERPRETER = "{{ cookiecutter.python_interpreter }}"


def create_png(width: int, height: int, color: tuple) -> bytes:
    """创建简单的纯色 RGBA PNG 图片。"""
    def png_chunk(chunk_type: bytes, data: bytes) -> bytes:
        chunk_len = struct.pack(">I", len(data))
        chunk_crc = struct.pack(">I", zlib.crc32(chunk_type + data) & 0xFFFFFFFF)
        return chunk_len + chunk_type + data + chunk_crc

    # PNG 签名
    signature = b"\x89PNG\r\n\x1a\n"

    # IHDR 块 - color_type=6 表示 RGBA
    ihdr_data = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    ihdr = png_chunk(b"IHDR", ihdr_data)

    # IDAT 块 - 图像数据 (RGBA)
    raw_data = b""
    r, g, b = color[:3]
    a = color[3] if len(color) > 3 else 255
    pixel = bytes([r, g, b, a])
    row = b"\x00" + pixel * width  # 滤波类型 + 像素数据
    raw_data = row * height
    
    compressed = zlib.compress(raw_data, 9)
    idat = png_chunk(b"IDAT", compressed)

    # IEND 块
    iend = png_chunk(b"IEND", b"")

    return signature + ihdr + idat + iend


def generate_default_icons() -> None:
    """生成默认应用图标。"""
    icons_dir = os.path.join(PROJECT_DIR, "src-tauri", "icons")
    os.makedirs(icons_dir, exist_ok=True)

    # Tauri 默认主题色
    tauri_color = (36, 200, 219)  # #24C8DB

    icon_sizes = {
        "32x32.png": 32,
        "128x128.png": 128,
        "128x128@2x.png": 256,
    }

    for filename, size in icon_sizes.items():
        icon_path = os.path.join(icons_dir, filename)
        if not os.path.exists(icon_path):
            png_data = create_png(size, size, tauri_color)
            with open(icon_path, "wb") as f:
                f.write(png_data)

    # 生成 .icns (macOS) - 使用简化版本
    icns_path = os.path.join(icons_dir, "icon.icns")
    if not os.path.exists(icns_path):
        # 简化的 ICNS：只包含 128x128 PNG
        png_128 = create_png(128, 128, tauri_color)
        icns_header = b"icns" + struct.pack(">I", 8 + 8 + len(png_128))
        icns_icon = b"ic07" + struct.pack(">I", 8 + len(png_128)) + png_128
        with open(icns_path, "wb") as f:
            f.write(icns_header + icns_icon)

    # 生成 .ico (Windows) - 简化版本
    ico_path = os.path.join(icons_dir, "icon.ico")
    if not os.path.exists(ico_path):
        png_32 = create_png(32, 32, tauri_color)
        # ICO 文件头
        ico_header = struct.pack("<HHH", 0, 1, 1)  # 保留, 类型(1=ICO), 图片数量
        # 图片目录条目
        ico_entry = struct.pack(
            "<BBBBHHII",
            32, 32,  # 宽高
            0, 0,    # 调色板, 保留
            1, 32,   # 颜色平面, 位深度
            len(png_32),  # 数据大小
            22  # 数据偏移 (6 + 16)
        )
        with open(ico_path, "wb") as f:
            f.write(ico_header + ico_entry + png_32)

    print("  [+] 默认图标已生成")


def remove_file(path: str) -> None:
    """删除文件（如果存在）。"""
    full_path = os.path.join(PROJECT_DIR, path)
    if os.path.exists(full_path):
        os.remove(full_path)
        print(f"  已删除: {path}")


def remove_directory(path: str) -> None:
    """删除目录（如果存在）。"""
    full_path = os.path.join(PROJECT_DIR, path)
    if os.path.exists(full_path):
        shutil.rmtree(full_path)
        print(f"  已删除: {path}")


def update_package_json() -> None:
    """更新 package.json，移除不需要的依赖。"""
    pkg_path = os.path.join(PROJECT_DIR, "package.json")
    
    with open(pkg_path, "r") as f:
        pkg = json.load(f)
    
    # 添加可选依赖
    if INCLUDE_TAILWIND:
        pkg["devDependencies"]["tailwindcss"] = "^3.4.0"
        pkg["devDependencies"]["postcss"] = "^8.4.0"
        pkg["devDependencies"]["autoprefixer"] = "^10.4.0"
    
    if INCLUDE_UPDATER:
        pkg["dependencies"]["@tauri-apps/plugin-updater"] = "^2.0.0"
        pkg["dependencies"]["@tauri-apps/plugin-process"] = "^2.0.0"
    
    if INCLUDE_FS:
        pkg["dependencies"]["@tauri-apps/plugin-fs"] = "^2.0.0"
        pkg["dependencies"]["@tauri-apps/plugin-dialog"] = "^2.0.0"
    
    if INCLUDE_PYTHON:
        pkg["dependencies"]["tauri-plugin-python-api"] = "^0.3.0"
    
    # 排序依赖
    if "dependencies" in pkg:
        pkg["dependencies"] = dict(sorted(pkg["dependencies"].items()))
    if "devDependencies" in pkg:
        pkg["devDependencies"] = dict(sorted(pkg["devDependencies"].items()))
    
    with open(pkg_path, "w") as f:
        json.dump(pkg, f, indent=2)
        f.write("\n")


def update_cargo_toml() -> None:
    """更新 Cargo.toml，添加可选依赖。"""
    cargo_path = os.path.join(PROJECT_DIR, "src-tauri", "Cargo.toml")
    
    with open(cargo_path, "r") as f:
        content = f.read()
    
    extra_deps = []
    
    if INCLUDE_TRAY:
        extra_deps.append('tauri-plugin-shell = "2"')
    
    if INCLUDE_UPDATER:
        extra_deps.append('tauri-plugin-updater = "2"')
        extra_deps.append('tauri-plugin-process = "2"')
    
    if INCLUDE_FS:
        extra_deps.append('tauri-plugin-fs = "2"')
        extra_deps.append('tauri-plugin-dialog = "2"')
    
    if INCLUDE_PYTHON:
        if PYTHON_INTERPRETER == "pyo3":
            extra_deps.append('tauri-plugin-python = { version = "0.3", features = ["pyo3"] }')
        else:
            extra_deps.append('tauri-plugin-python = "0.3"')
    
    if extra_deps:
        # 在 serde_json 后添加新依赖
        insert_point = 'serde_json = "1"'
        new_deps = insert_point + "\n" + "\n".join(extra_deps)
        content = content.replace(insert_point, new_deps)
    
    with open(cargo_path, "w") as f:
        f.write(content)


def update_lib_rs() -> None:
    """更新 lib.rs，配置可选功能。"""
    lib_path = os.path.join(PROJECT_DIR, "src-tauri", "src", "lib.rs")
    
    with open(lib_path, "r") as f:
        content = f.read()
    
    plugins = [".plugin(tauri_plugin_shell::init())"]
    
    if INCLUDE_UPDATER:
        plugins.append(".plugin(tauri_plugin_updater::Builder::new().build())")
        plugins.append(".plugin(tauri_plugin_process::init())")
    
    if INCLUDE_FS:
        plugins.append(".plugin(tauri_plugin_fs::init())")
        plugins.append(".plugin(tauri_plugin_dialog::init())")
    
    if INCLUDE_PYTHON:
        plugins.append('.plugin(tauri_plugin_python::init_and_register(vec!["greet_python"]))')
    
    # 构建 setup 代码
    setup_code = ""
    if INCLUDE_TRAY:
        content = content.replace(
            "use tauri::Manager;",
            "mod tray;\n\nuse tauri::Manager;"
        )
        setup_code = """
            // 初始化系统托盘
            tray::init(app)?;
"""
    
    # 替换插件链
    plugin_chain = "\n        ".join(plugins)
    
    new_builder = (
        f"tauri::Builder::default()\n"
        f"        {plugin_chain}\n"
        f"        .setup(|app| {LBRACE}\n"
        f"            {HASH}[cfg(debug_assertions)]\n"
        f"            {LBRACE}\n"
        f"                let window = app.get_webview_window(\"main\").unwrap();\n"
        f"                window.open_devtools();\n"
        f"            {RBRACE}{setup_code}\n"
        f"            Ok(())\n"
        f"        {RBRACE})"
    )
    
    # 简化替换：整个 Builder 链
    old_builder = (
        f"tauri::Builder::default()\n"
        f"        .plugin(tauri_plugin_shell::init())\n"
        f"        .setup(|app| {LBRACE}\n"
        f"            {HASH}[cfg(debug_assertions)]\n"
        f"            {LBRACE}\n"
        f"                let window = app.get_webview_window(\"main\").unwrap();\n"
        f"                window.open_devtools();\n"
        f"            {RBRACE}\n"
        f"            Ok(())\n"
        f"        {RBRACE})"
    )
    
    content = content.replace(old_builder, new_builder)
    
    with open(lib_path, "w") as f:
        f.write(content)


def update_tauri_conf() -> None:
    """更新 tauri.conf.json 配置。"""
    conf_path = os.path.join(PROJECT_DIR, "src-tauri", "tauri.conf.json")
    
    with open(conf_path, "r") as f:
        conf = json.load(f)
    
    # 添加更新器配置
    if INCLUDE_UPDATER:
        conf["plugins"] = conf.get("plugins", {})
        # 构造 URL 模板，避免 Jinja2 解析双括号
        url_template = f"https://releases.example.com/{LBRACE}{LBRACE}target{RBRACE}{RBRACE}/{LBRACE}{LBRACE}arch{RBRACE}{RBRACE}/{LBRACE}{LBRACE}current_version{RBRACE}{RBRACE}"
        conf["plugins"]["updater"] = {
            "pubkey": "",
            "endpoints": [url_template]
        }
    
    # 添加 Python 资源打包配置
    if INCLUDE_PYTHON:
        if "bundle" not in conf:
            conf["bundle"] = {}
        if "resources" not in conf["bundle"]:
            conf["bundle"]["resources"] = {}
        # 使用字典格式，避免 Jinja2 解析问题
        conf["bundle"]["resources"]["src-python/"] = "src-python/"
    
    with open(conf_path, "w") as f:
        json.dump(conf, f, indent=2)
        f.write("\n")


def update_default_capability() -> None:
    """更新 default.json 权限配置。"""
    default_path = os.path.join(PROJECT_DIR, "src-tauri", "capabilities", "default.json")
    
    with open(default_path, "r") as f:
        default_conf = json.load(f)
    
    # 添加 Python 权限
    if INCLUDE_PYTHON:
        if "python:default" not in default_conf["permissions"]:
            default_conf["permissions"].append("python:default")
    
    with open(default_path, "w") as f:
        json.dump(default_conf, f, indent=2)
        f.write("\n")


def cleanup_optional_modules() -> None:
    """删除不需要的可选模块。"""
    
    # TailwindCSS
    if not INCLUDE_TAILWIND:
        remove_file("tailwind.config.js")
        remove_file("postcss.config.js")
        print("  [-] TailwindCSS 已排除")
    else:
        print("  [+] TailwindCSS 已包含")
    
    # 国际化
    if not INCLUDE_I18N:
        remove_directory("src/lib/i18n")
        print("  [-] 国际化模块已排除")
    else:
        print("  [+] 国际化模块已包含")
    
    # 系统托盘
    if not INCLUDE_TRAY:
        remove_file("src-tauri/src/tray.rs")
        remove_file("src-tauri/capabilities/tray.json")
        print("  [-] 系统托盘已排除")
    else:
        print("  [+] 系统托盘已包含")
    
    # 自动更新
    if not INCLUDE_UPDATER:
        remove_file("src/lib/tauri/updater.ts")
        remove_file("src-tauri/capabilities/updater.json")
        print("  [-] 自动更新已排除")
    else:
        print("  [+] 自动更新已包含")
    
    # 文件系统
    if not INCLUDE_FS:
        remove_file("src/lib/tauri/fs.ts")
        remove_file("src-tauri/capabilities/fs.json")
        print("  [-] 文件系统 API 已排除")
    else:
        print("  [+] 文件系统 API 已包含")
    
    # Python 后端
    if not INCLUDE_PYTHON:
        remove_directory("src-tauri/src-python")
        remove_file("src-tauri/capabilities/python.json")
        print("  [-] Python 后端已排除")
    else:
        print(f"  [+] Python 后端已包含 ({PYTHON_INTERPRETER})")
    
    # 清理空的 tauri 目录
    tauri_lib_dir = os.path.join(PROJECT_DIR, "src/lib/tauri")
    if os.path.exists(tauri_lib_dir):
        remaining = os.listdir(tauri_lib_dir)
        if not remaining or remaining == ["index.ts"]:
            # 更新 index.ts 或删除目录
            if not INCLUDE_UPDATER and not INCLUDE_FS:
                remove_directory("src/lib/tauri")
            else:
                # 更新 index.ts 内容
                index_path = os.path.join(tauri_lib_dir, "index.ts")
                exports = []
                if INCLUDE_FS:
                    exports.append('export * from "./fs";')
                if INCLUDE_UPDATER:
                    exports.append('export * from "./updater";')
                
                with open(index_path, "w") as f:
                    f.write("// Generated by Cursor\n")
                    f.write("\n".join(exports) + "\n")
    
    # 清理空的 stores 目录（如果不需要）
    stores_dir = os.path.join(PROJECT_DIR, "src/lib/stores")
    if not os.path.exists(stores_dir) or not os.listdir(stores_dir):
        remove_directory("src/lib/stores")


def main() -> None:
    """主入口。"""
    print("\n> 处理项目配置...\n")
    
    # 生成默认图标
    print("[图标生成]")
    generate_default_icons()
    
    print("\n[可选模块]")
    
    # 清理可选模块
    cleanup_optional_modules()
    
    # 更新配置文件
    print("\n[配置更新]")
    update_package_json()
    print("  package.json 已更新")
    
    update_cargo_toml()
    print("  Cargo.toml 已更新")
    
    update_lib_rs()
    print("  lib.rs 已更新")
    
    update_tauri_conf()
    print("  tauri.conf.json 已更新")
    
    update_default_capability()
    print("  default.json 已更新")
    
    print("\n[完成] 项目生成成功\n")
    print("后续步骤:")
    print(f"  1. cd {PROJECT_NAME}")
    print("  2. pnpm install")
    print("  3. pnpm tauri dev")
    print("\n提示: 可使用 'pnpm tauri icon <source.png>' 替换默认图标")


if __name__ == "__main__":
    main()

