// Generated by Cursor
import Foundation

// MARK: - Example Entity

/// Domain entity - pure data model without framework dependencies.
/// Add your domain entities here.
struct ExampleEntity: Identifiable, Equatable, Sendable {
    let id: String
    let title: String
    let createdAt: Date
}

// MARK: - Entity Extensions

extension ExampleEntity {
    static let preview = ExampleEntity(
        id: UUID().uuidString,
        title: "Preview Item",
        createdAt: .now
    )
}

