// Generated by Cursor
import ArgumentParser

@main
struct {{cookiecutter.project_name}}: ParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "{{cookiecutter.project_name | lower}}",
        abstract: "{{cookiecutter.description}}",
        version: "1.0.0",
        subcommands: [Run.self, Info.self],
        defaultSubcommand: Run.self
    )
}

// MARK: - Run 子命令
struct Run: ParsableCommand {
    static let configuration = CommandConfiguration(
        abstract: "执行主要功能"
    )
    
    @Option(name: .shortAndLong, help: "输入文件路径")
    var input: String?
    
    @Flag(name: .shortAndLong, help: "显示详细输出")
    var verbose = false
    
    func run() throws {
        if verbose {
            print("[{{cookiecutter.project_name}}] 开始执行...")
        }
        
        if let input = input {
            print("处理输入: \(input)")
        } else {
            print("Hello from {{cookiecutter.project_name}}!")
        }
        
        if verbose {
            print("[{{cookiecutter.project_name}}] 执行完成")
        }
    }
}

// MARK: - Info 子命令
struct Info: ParsableCommand {
    static let configuration = CommandConfiguration(
        abstract: "显示工具信息"
    )
    
    func run() throws {
        print("""
        {{cookiecutter.project_name}}
        版本: 1.0.0
        作者: {{cookiecutter.author_name}}
        描述: {{cookiecutter.description}}
        """)
    }
}

