# Generated by Cursor
# Python backend functions for {{ cookiecutter.project_name }}

# List of functions that can be called from the frontend
_tauri_plugin_functions = ["greet_python"]

def greet_python(name: str) -> str:
    """
    Example Python function that can be called from the frontend.
    
    Args:
        name: A string parameter from JavaScript
        
    Returns:
        A greeting message from Python
    """
    return f"Hello, {name}! From Python 🐍"

