// Generated by Cursor
import Factory
import Foundation

// MARK: - Container Extensions

extension Container {
    
    #if os(iOS)
    // MARK: - Coordinators (iOS only)
    
    var appCoordinator: Factory<AppCoordinator> {
        self { MainActor.assumeIsolated { AppCoordinator() } }
            .singleton
    }
    #endif
    
    // MARK: - ViewModels
    
    var homeViewModel: Factory<HomeViewModel> {
        self { MainActor.assumeIsolated { HomeViewModel() } }
    }
    
    // MARK: - UseCases
    
    // Register your use cases here
    // var someUseCase: Factory<SomeUseCaseProtocol> {
    //     self { SomeUseCase(repository: self.someRepository()) }
    // }
    
    // MARK: - Repositories
    
    // Register your repositories here
    // var someRepository: Factory<SomeRepositoryProtocol> {
    //     self { SomeRepository() }
    // }
    
    {% if cookiecutter.include_network == 'yes' %}
    // MARK: - Network
    
    var networkClient: Factory<NetworkClientProtocol> {
        self { NetworkClient() }
            .singleton
    }
    {% endif %}
    
    {% if cookiecutter.include_persistence == 'yes' %}
    // MARK: - Persistence
    
    var swiftDataStore: Factory<SwiftDataStoreProtocol> {
        self { MainActor.assumeIsolated { SwiftDataStore() } }
            .singleton
    }
    {% endif %}
}
