// Generated by Cursor
// {{cookiecutter.package_name}} - SwiftUI Components

#if canImport(SwiftUI)
import SwiftUI

/// Example SwiftUI view component.
@available(iOS 17.0, macOS 14.0, *)
public struct ExampleView: View {
    private let title: String
    
    /// Creates an ExampleView with the given title.
    /// - Parameter title: The title to display.
    public init(title: String = "{{cookiecutter.package_name}}") {
        self.title = title
    }
    
    public var body: some View {
        VStack(spacing: 16) {
            Text(title)
                .font(.title)
                .fontWeight(.bold)
            
            Text("Version: \({{cookiecutter.package_name}}.version)")
                .font(.caption)
                .foregroundStyle(.secondary)
        }
        .padding()
    }
}

@available(iOS 17.0, macOS 14.0, *)
#Preview {
    ExampleView()
}
#endif

