#!/bin/bash
# Generated by Cursor
# Tauri + Svelte 项目生成器 - 启动脚本

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLI_DIR="$SCRIPT_DIR/cli"
VENV_DIR="$CLI_DIR/.venv"

# 颜色
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

print_step() {
    printf "%b\n" "${CYAN}>${NC} $1"
}

print_success() {
    printf "%b\n" "${GREEN}[OK]${NC} $1"
}

print_warning() {
    printf "%b\n" "${YELLOW}[警告]${NC} $1"
}

print_error() {
    printf "%b\n" "${RED}[错误]${NC} $1"
}

# 检查 Python 安装
check_python() {
    if command -v python3 &> /dev/null; then
        PYTHON_CMD="python3"
    elif command -v python &> /dev/null; then
        PYTHON_CMD="python"
    else
        print_error "未找到 Python，请安装 Python 3.9+"
        exit 1
    fi
    
    PYTHON_VERSION=$($PYTHON_CMD -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
    print_success "Python $PYTHON_VERSION"
}

# 检查 pip 安装
check_pip() {
    if command -v uv &> /dev/null; then
        PIP_CMD="uv pip"
        print_success "uv $(uv --version | cut -d' ' -f2)"
    elif command -v pip3 &> /dev/null; then
        PIP_CMD="pip3"
        print_success "pip3 $(pip3 --version | cut -d' ' -f2)"
    elif command -v pip &> /dev/null; then
        PIP_CMD="pip"
        print_success "pip $(pip --version | cut -d' ' -f2)"
    else
        PIP_CMD="$PYTHON_CMD -m pip"
        print_success "pip (via python -m pip)"
    fi
}

# 检查 Rust 安装
check_rust() {
    if command -v rustc &> /dev/null; then
        RUST_VERSION=$(rustc --version | cut -d' ' -f2)
        print_success "Rust: $RUST_VERSION"
    else
        print_warning "未找到 Rust"
        echo ""
        read -p "是否通过 rustup 安装 Rust? [Y/n] " -n 1 -r
        echo ""
        if [[ $REPLY =~ ^[Yy]$ ]] || [[ -z $REPLY ]]; then
            print_step "正在安装 Rust..."
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source "$HOME/.cargo/env"
            print_success "Rust 安装完成"
        else
            print_warning "需要 Rust，稍后可执行: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
        fi
    fi
}

# 检查 pnpm 安装
check_pnpm() {
    if command -v pnpm &> /dev/null; then
        PNPM_VERSION=$(pnpm --version)
        print_success "pnpm: $PNPM_VERSION"
    else
        print_warning "未找到 pnpm"
        echo ""
        read -p "是否通过 npm 安装 pnpm? [Y/n] " -n 1 -r
        echo ""
        if [[ $REPLY =~ ^[Yy]$ ]] || [[ -z $REPLY ]]; then
            print_step "正在安装 pnpm..."
            npm install -g pnpm
            print_success "pnpm 安装完成"
        else
            print_warning "需要 pnpm，稍后可执行: npm install -g pnpm"
        fi
    fi
}

# 显示旋转进度指示器
spin() {
    local pid=$1
    local msg=$2
    local -a spinchars=('-' '\' '|' '/')
    local i=0
    
    printf "  ${CYAN}%s${NC} %s" "-" "$msg"
    
    while kill -0 "$pid" 2>/dev/null; do
        i=$(( (i + 1) % 4 ))
        printf "\r  ${CYAN}%s${NC} %s" "${spinchars[$i]}" "$msg"
        sleep 0.1
    done
    
    wait "$pid"
    local exit_code=$?
    
    printf "\r\033[K"
    
    return $exit_code
}

# 运行命令并显示进度
run_with_progress() {
    local msg=$1
    shift
    
    "$@" >/dev/null 2>&1 &
    local pid=$!
    
    spin $pid "$msg"
    local exit_code=$?
    
    if [[ $exit_code -eq 0 ]]; then
        print_success "$msg"
    else
        print_error "$msg 失败"
        return $exit_code
    fi
}

# 设置虚拟环境并安装依赖
setup_venv() {
    if [ ! -d "$VENV_DIR" ]; then
        run_with_progress "创建虚拟环境" $PYTHON_CMD -m venv "$VENV_DIR"
    fi
    
    source "$VENV_DIR/bin/activate"
    
    # 安装依赖（带进度）
    if [[ "$PIP_CMD" == "uv pip" ]]; then
        run_with_progress "升级 pip" uv pip install --upgrade pip || true
        run_with_progress "安装依赖" uv pip install -r "$CLI_DIR/requirements.txt"
    else
        run_with_progress "升级 pip" "$VENV_DIR/bin/pip" install --upgrade pip
        run_with_progress "安装依赖" "$VENV_DIR/bin/pip" install -r "$CLI_DIR/requirements.txt"
    fi
}

# 主函数
main() {
    echo ""
    printf "%b\n" "${CYAN}========================================${NC}"
    printf "%b\n" "${CYAN}  Tauri + Svelte 项目生成器             ${NC}"
    printf "%b\n" "${CYAN}  Tauri 2.0 + Svelte 5 (Runes)         ${NC}"
    printf "%b\n" "${CYAN}========================================${NC}"
    echo ""
    
    print_step "检查依赖..."
    echo ""
    
    check_python
    check_pip
    check_rust
    check_pnpm
    
    echo ""
    setup_venv
    
    echo ""
    print_step "启动交互式配置..."
    echo ""
    
    # 运行 CLI，传递所有参数
    "$VENV_DIR/bin/python" "$CLI_DIR/create_project.py" "$@"
}

main "$@"

