// Generated by Cursor
// {{cookiecutter.package_name}} - Main Entry Point

{% if cookiecutter.include_ui == "yes" -%}
#if canImport(SwiftUI)
import SwiftUI
#endif
{% endif -%}

/// {{cookiecutter.package_name}} library namespace.
public enum {{cookiecutter.package_name}} {
    /// Library version.
    public static let version = "1.0.0"
}

