// swift-tools-version: 5.10
// Generated by Cursor
import PackageDescription

let package = Package(
    name: "{{cookiecutter.package_name}}",
    {% if cookiecutter.platforms == "iOS" -%}
    platforms: [
        .iOS(.v{{cookiecutter.ios_deployment_target | replace(".", "_") | replace("_0", "")}})
    ],
    {% elif cookiecutter.platforms == "macOS" -%}
    platforms: [
        .macOS(.v{{cookiecutter.macos_deployment_target | replace(".", "_") | replace("_0", "")}})
    ],
    {% else -%}
    platforms: [
        .iOS(.v{{cookiecutter.ios_deployment_target | replace(".", "_") | replace("_0", "")}}),
        .macOS(.v{{cookiecutter.macos_deployment_target | replace(".", "_") | replace("_0", "")}})
    ],
    {% endif -%}
    products: [
        .library(
            name: "{{cookiecutter.package_name}}",
            targets: ["{{cookiecutter.package_name}}"]
        )
    ],
    targets: [
        .target(
            name: "{{cookiecutter.package_name}}",
            path: "Sources/{{cookiecutter.package_name}}"
        ),
        .testTarget(
            name: "{{cookiecutter.package_name}}Tests",
            dependencies: ["{{cookiecutter.package_name}}"],
            path: "Tests/{{cookiecutter.package_name}}Tests"
        )
    ]
)

