<script lang="ts">
  // Generated by Cursor
  import { invoke } from "@tauri-apps/api/core";

  let name = $state("");
  let greeting = $state("");
  let isLoading = $state(false);

  async function greet() {
    if (!name.trim()) return;
    isLoading = true;
    try {
      greeting = await invoke("greet", { name });
    } finally {
      isLoading = false;
    }
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === "Enter") greet();
  }
</script>

<main>
  <header>
    <h1>{{ cookiecutter.project_name }}</h1>
    <p class="tagline">Powered by Tauri + Svelte 5</p>
  </header>

  <section class="card">
    <div class="input-group">
      <input
        type="text"
        bind:value={name}
        onkeydown={handleKeydown}
        placeholder="Enter your name..."
        disabled={isLoading}
      />
      <button onclick={greet} disabled={isLoading || !name.trim()}>
        {isLoading ? "..." : "Greet"}
      </button>
    </div>

    {% raw %}{#if greeting}{% endraw %}
      <p class="greeting">{greeting}</p>
    {% raw %}{/if}{% endraw %}
  </section>

  <footer>
    <p>
      Built with
      <a href="https://tauri.app" target="_blank" rel="noopener">Tauri</a>
      and
      <a href="https://svelte.dev" target="_blank" rel="noopener">Svelte 5</a>
    </p>
  </footer>
</main>

<style>
  main {
    flex: 1;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 2rem;
    gap: 2rem;
  }

  header {
    text-align: center;
  }

  h1 {
    font-size: 2.5rem;
    font-weight: 700;
    background: linear-gradient(135deg, var(--color-primary), var(--color-accent));
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
  }

  .tagline {
    color: var(--color-text-muted);
    margin-top: 0.5rem;
  }

  .card {
    background: var(--color-surface);
    border: 1px solid var(--color-border);
    border-radius: var(--radius);
    padding: 2rem;
    width: 100%;
    max-width: 400px;
    box-shadow: var(--shadow);
  }

  .input-group {
    display: flex;
    gap: 0.75rem;
  }

  .input-group input {
    flex: 1;
  }

  .greeting {
    margin-top: 1.5rem;
    padding: 1rem;
    background: var(--color-bg);
    border-radius: var(--radius);
    text-align: center;
    font-size: 1.1rem;
    animation: fadeIn 0.3s ease;
  }

  @keyframes fadeIn {
    from {
      opacity: 0;
      transform: translateY(-8px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }

  footer {
    color: var(--color-text-muted);
    font-size: 0.9rem;
  }
</style>

