#!/bin/bash
# Generated by Cursor
# Swift CLI 生成器 - 启动脚本

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLI_DIR="$SCRIPT_DIR/cli"
VENV_DIR="$CLI_DIR/.venv"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

print_step() {
    printf "%b\n" "${CYAN}>${NC} $1"
}

print_success() {
    printf "%b\n" "${GREEN}[OK]${NC} $1"
}

print_warning() {
    printf "%b\n" "${YELLOW}[警告]${NC} $1"
}

print_error() {
    printf "%b\n" "${RED}[错误]${NC} $1"
}

check_python() {
    if command -v python3 &> /dev/null; then
        PYTHON_CMD="python3"
    elif command -v python &> /dev/null; then
        PYTHON_CMD="python"
    else
        print_error "未找到 Python，请安装 Python 3.9+"
        exit 1
    fi
    
    PYTHON_VERSION=$($PYTHON_CMD -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
    print_success "Python $PYTHON_VERSION"
}

check_pip() {
    if command -v uv &> /dev/null; then
        PIP_CMD="uv pip"
        print_success "uv $(uv --version | cut -d' ' -f2)"
    elif command -v pip3 &> /dev/null; then
        PIP_CMD="pip3"
        print_success "pip3 $(pip3 --version | cut -d' ' -f2)"
    elif command -v pip &> /dev/null; then
        PIP_CMD="pip"
        print_success "pip $(pip --version | cut -d' ' -f2)"
    else
        PIP_CMD="$PYTHON_CMD -m pip"
        print_success "pip (via python -m pip)"
    fi
}

setup_venv() {
    if [ ! -d "$VENV_DIR" ]; then
        print_step "创建虚拟环境..."
        $PYTHON_CMD -m venv "$VENV_DIR"
        print_success "虚拟环境已创建"
    fi
    
    print_step "激活虚拟环境..."
    source "$VENV_DIR/bin/activate"
    
    print_step "安装依赖..."
    if [[ "$PIP_CMD" == "uv pip" ]]; then
        uv pip install --python "$VENV_DIR/bin/python" --quiet --upgrade pip
        uv pip install --python "$VENV_DIR/bin/python" --quiet -r "$CLI_DIR/requirements.txt"
    else
        $PIP_CMD install --quiet --upgrade pip
        $PIP_CMD install --quiet -r "$CLI_DIR/requirements.txt"
    fi
    print_success "依赖安装完成"
}

main() {
    echo ""
    printf "%b\n" "${CYAN}========================================${NC}"
    printf "%b\n" "${CYAN}  Swift CLI 生成器                      ${NC}"
    printf "%b\n" "${CYAN}  macOS 命令行工具模板                   ${NC}"
    printf "%b\n" "${CYAN}========================================${NC}"
    echo ""
    
    print_step "检查依赖..."
    echo ""
    
    check_python
    check_pip
    
    echo ""
    setup_venv
    
    echo ""
    print_step "启动交互式配置..."
    echo ""
    
    "$VENV_DIR/bin/python" "$CLI_DIR/create_project.py" "$@"
}

main "$@"

