#!/bin/bash
# Generated by Cursor
# Swift CLI 生成器 - 启动脚本

set -e

if [ -z "${BASH_VERSION:-}" ]; then
    echo "请使用 bash 运行：bash create_project.sh 或 ./create_project.sh"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLI_DIR="$SCRIPT_DIR/cli"
VENV_DIR="$CLI_DIR/.venv"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

print_step() {
    printf "%b\n" "${CYAN}>${NC} $1"
}

print_success() {
    printf "%b\n" "${GREEN}[OK]${NC} $1"
}

print_warning() {
    printf "%b\n" "${YELLOW}[警告]${NC} $1"
}

print_error() {
    printf "%b\n" "${RED}[错误]${NC} $1"
}

check_python() {
    if command -v python3 &> /dev/null; then
        PYTHON_CMD="python3"
    elif command -v python &> /dev/null; then
        PYTHON_CMD="python"
    else
        print_error "未找到 Python，请安装 Python 3.9+"
        exit 1
    fi
    
    PYTHON_VERSION=$($PYTHON_CMD -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
    print_success "Python $PYTHON_VERSION"
}

check_pip() {
    if command -v uv &> /dev/null; then
        PIP_CMD="uv pip"
        print_success "uv $(uv --version | cut -d' ' -f2)"
    elif command -v pip3 &> /dev/null; then
        PIP_CMD="pip3"
        print_success "pip3 $(pip3 --version | cut -d' ' -f2)"
    elif command -v pip &> /dev/null; then
        PIP_CMD="pip"
        print_success "pip $(pip --version | cut -d' ' -f2)"
    else
        PIP_CMD="$PYTHON_CMD -m pip"
        print_success "pip (via python -m pip)"
    fi
}

# 显示旋转进度指示器
spin() {
    local pid=$1
    local msg=$2
    local -a spinchars=('-' '\' '|' '/')
    local i=0
    
    printf "  ${CYAN}%s${NC} %s" "-" "$msg"
    
    while kill -0 "$pid" 2>/dev/null; do
        i=$(( (i + 1) % 4 ))
        printf "\r  ${CYAN}%s${NC} %s" "${spinchars[$i]}" "$msg"
        sleep 0.1
    done
    
    wait "$pid"
    local exit_code=$?
    
    printf "\r\033[K"
    
    return $exit_code
}

# 运行命令并显示进度
run_with_progress() {
    local msg=$1
    shift
    
    "$@" >/dev/null 2>&1 &
    local pid=$!
    
    spin $pid "$msg"
    local exit_code=$?
    
    if [[ $exit_code -eq 0 ]]; then
        print_success "$msg"
    else
        print_error "$msg 失败"
        return $exit_code
    fi
}

setup_venv() {
    if [ ! -d "$VENV_DIR" ]; then
        run_with_progress "创建虚拟环境" $PYTHON_CMD -m venv "$VENV_DIR"
    fi
    
    source "$VENV_DIR/bin/activate"
    
    # 安装依赖（带进度）
    if [[ "$PIP_CMD" == "uv pip" ]]; then
        # uv 不需要升级 pip，需要显式指定 Python 路径
        run_with_progress "安装依赖" uv pip install --python "$VENV_DIR/bin/python" -r "$CLI_DIR/requirements.txt"
    else
        run_with_progress "升级 pip" "$VENV_DIR/bin/pip" install --upgrade pip || true
        run_with_progress "安装依赖" "$VENV_DIR/bin/pip" install -r "$CLI_DIR/requirements.txt"
    fi
}

main() {
    echo ""
    printf "%b\n" "${CYAN}========================================${NC}"
    printf "%b\n" "${CYAN}  Swift CLI 生成器                      ${NC}"
    printf "%b\n" "${CYAN}  macOS 命令行工具模板                   ${NC}"
    printf "%b\n" "${CYAN}========================================${NC}"
    echo ""
    
    print_step "检查依赖..."
    echo ""
    
    check_python
    check_pip
    
    echo ""
    setup_venv
    
    echo ""
    print_step "启动交互式配置..."
    echo ""
    
    "$VENV_DIR/bin/python" "$CLI_DIR/create_project.py" "$@"
}

main "$@"

