// Generated by Cursor
import Testing
@testable import {{cookiecutter.project_name}}

@Suite("{{cookiecutter.project_name}} Tests")
struct {{cookiecutter.project_name}}Tests {
    
    @Test("Example test")
    func exampleTest() async throws {
        #expect(true)
    }
}

