// Generated by Cursor
import Foundation

// MARK: - Use Case Protocol

/// Base protocol for all use cases.
/// Each use case represents a single business operation.
protocol UseCase {
    associatedtype Input
    associatedtype Output
    
    func execute(_ input: Input) async throws -> Output
}

// MARK: - Example Use Case

protocol FetchExamplesUseCaseProtocol: Sendable {
    func execute() async throws -> [ExampleEntity]
}

final class FetchExamplesUseCase: FetchExamplesUseCaseProtocol, Sendable {
    private let repository: ExampleRepositoryProtocol
    
    init(repository: ExampleRepositoryProtocol) {
        self.repository = repository
    }
    
    func execute() async throws -> [ExampleEntity] {
        try await repository.fetchAll()
    }
}

// MARK: - Save Example Use Case

protocol SaveExampleUseCaseProtocol: Sendable {
    func execute(_ entity: ExampleEntity) async throws
}

final class SaveExampleUseCase: SaveExampleUseCaseProtocol, Sendable {
    private let repository: ExampleRepositoryProtocol
    
    init(repository: ExampleRepositoryProtocol) {
        self.repository = repository
    }
    
    func execute(_ entity: ExampleEntity) async throws {
        try await repository.save(entity)
    }
}

