// Generated by Cursor
import Foundation

// MARK: - Example Repository Implementation

final class ExampleRepository: ExampleRepositoryProtocol, Sendable {
    {% if cookiecutter.include_network == 'yes' %}
    private let networkClient: NetworkClientProtocol
    {% endif %}
    {% if cookiecutter.include_persistence == 'yes' %}
    private let store: SwiftDataStoreProtocol
    {% endif %}
    
    init(
        {% if cookiecutter.include_network == 'yes' %}
        networkClient: NetworkClientProtocol{% if cookiecutter.include_persistence == 'yes' %},{% endif %}
        {% endif %}
        {% if cookiecutter.include_persistence == 'yes' %}
        store: SwiftDataStoreProtocol
        {% endif %}
    ) {
        {% if cookiecutter.include_network == 'yes' %}
        self.networkClient = networkClient
        {% endif %}
        {% if cookiecutter.include_persistence == 'yes' %}
        self.store = store
        {% endif %}
    }
    
    func fetchAll() async throws -> [ExampleEntity] {
        // TODO: Implement with actual data source
        // Example:
        // {% if cookiecutter.include_network == 'yes' %}
        // let dtos = try await networkClient.request(ExampleEndpoint.list)
        // return dtos.map { $0.toEntity() }
        // {% endif %}
        []
    }
    
    func fetch(by id: String) async throws -> ExampleEntity? {
        // TODO: Implement
        nil
    }
    
    func save(_ entity: ExampleEntity) async throws {
        // TODO: Implement
    }
    
    func delete(by id: String) async throws {
        // TODO: Implement
    }
}

