// Generated by Cursor
/**
 * 国际化模块 - Svelte 5 Runes
 */

import en from "./locales/en.json";
import zh from "./locales/zh.json";

export type Locale = "en" | "zh";
export type TranslationKey = keyof typeof en;

const translations: Record<Locale, Record<string, string>> = {
  en,
  zh,
};

class I18n {
  locale = $state<Locale>("{{ cookiecutter.default_locale }}" as Locale);

  /** 获取可用语言列表 */
  get availableLocales(): Locale[] {
    return Object.keys(translations) as Locale[];
  }

  /** 切换语言 */
  setLocale(locale: Locale) {
    if (translations[locale]) {
      this.locale = locale;
      document.documentElement.lang = locale;
    }
  }

  /** 翻译文本 */
  t(key: string, params?: Record<string, string | number>): string {
    let text = translations[this.locale]?.[key] ?? translations.en[key] ?? key;

    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
      });
    }

    return text;
  }
}

export const i18n = new I18n();

/** 便捷翻译函数 */
export function t(key: string, params?: Record<string, string | number>): string {
  return i18n.t(key, params);
}

