// Generated by Cursor
import Foundation

// MARK: - HTTP Method

enum HTTPMethod: String {
    case get = "GET"
    case post = "POST"
    case put = "PUT"
    case patch = "PATCH"
    case delete = "DELETE"
}

// MARK: - Endpoint Protocol

protocol Endpoint {
    var baseURL: URL { get }
    var path: String { get }
    var method: HTTPMethod { get }
    var headers: [String: String] { get }
    var queryItems: [URLQueryItem]? { get }
    var body: Data? { get }
}

// MARK: - Default Implementation

extension Endpoint {
    var baseURL: URL {
        // TODO: Replace with your API base URL
        URL(string: "https://api.example.com")!
    }
    
    var headers: [String: String] {
        [
            "Content-Type": "application/json",
            "Accept": "application/json"
        ]
    }
    
    var queryItems: [URLQueryItem]? { nil }
    var body: Data? { nil }
    
    func urlRequest() throws -> URLRequest {
        var components = URLComponents(url: baseURL.appendingPathComponent(path), resolvingAgainstBaseURL: true)
        components?.queryItems = queryItems
        
        guard let url = components?.url else {
            throw APIError.invalidURL
        }
        
        var request = URLRequest(url: url)
        request.httpMethod = method.rawValue
        request.allHTTPHeaderFields = headers
        request.httpBody = body
        
        return request
    }
}

// MARK: - Example Endpoint

enum ExampleEndpoint: Endpoint {
    case list
    case detail(id: String)
    case create(data: Encodable)
    case update(id: String, data: Encodable)
    case delete(id: String)
    
    var path: String {
        switch self {
        case .list:
            return "/examples"
        case .detail(let id):
            return "/examples/\(id)"
        case .create:
            return "/examples"
        case .update(let id, _):
            return "/examples/\(id)"
        case .delete(let id):
            return "/examples/\(id)"
        }
    }
    
    var method: HTTPMethod {
        switch self {
        case .list, .detail:
            return .get
        case .create:
            return .post
        case .update:
            return .put
        case .delete:
            return .delete
        }
    }
    
    var body: Data? {
        switch self {
        case .create(let data), .update(_, let data):
            return try? JSONEncoder().encode(AnyEncodable(data))
        default:
            return nil
        }
    }
}

// MARK: - AnyEncodable

struct AnyEncodable: Encodable {
    private let encode: (Encoder) throws -> Void
    
    init(_ wrapped: Encodable) {
        encode = wrapped.encode
    }
    
    func encode(to encoder: Encoder) throws {
        try encode(encoder)
    }
}

