#!/usr/bin/env python3
# Generated by Cursor
"""
Cookiecutter 模板后处理钩子。
"""

import os

PROJECT_DIR = os.path.realpath(os.path.curdir)
PROJECT_NAME = "{{ cookiecutter.project_name }}"


def main() -> None:
    """主入口。"""
    print("\n> 处理项目配置...\n")
    
    print("[配置]")
    print(f"  项目名称: {PROJECT_NAME}")
    print("  类型: 命令行工具 (CLI)")
    print("  依赖: swift-argument-parser")
    
    print("\n[完成] CLI 项目生成成功\n")
    print("后续步骤:")
    print(f"  1. cd {PROJECT_NAME}")
    print("  2. swift build")
    print(f"  3. swift run {PROJECT_NAME}")
    print("\n发布构建:")
    print("  swift build -c release")
    print(f"  cp .build/release/{PROJECT_NAME} /usr/local/bin/")


if __name__ == "__main__":
    main()

