#!/usr/bin/env python3
# Generated by Cursor
"""
Cookiecutter 模板后处理钩子。
处理平台选择和可选 UI 模块。
"""

import os
import shutil

PROJECT_DIR = os.path.realpath(os.path.curdir)
PACKAGE_NAME = "{{ cookiecutter.package_name }}"

# 配置标志
PLATFORMS = "{{ cookiecutter.platforms }}"
INCLUDE_UI = "{{ cookiecutter.include_ui }}" == "yes"

# 平台标志
INCLUDE_IOS = PLATFORMS in ["iOS", "iOS and macOS"]
INCLUDE_MACOS = PLATFORMS in ["macOS", "iOS and macOS"]


def remove_directory(path: str) -> None:
    """删除目录（如果存在）。"""
    full_path = os.path.join(PROJECT_DIR, path)
    if os.path.exists(full_path):
        shutil.rmtree(full_path)
        print(f"  已删除: {path}")


def remove_file(path: str) -> None:
    """删除文件（如果存在）。"""
    full_path = os.path.join(PROJECT_DIR, path)
    if os.path.exists(full_path):
        os.remove(full_path)
        print(f"  已删除: {path}")


def main() -> None:
    """主入口。"""
    print("\n> 处理项目配置...\n")
    
    print("[平台]")
    if INCLUDE_IOS:
        print("  [+] iOS 平台已包含")
    else:
        print("  [-] iOS 平台已排除")
    
    if INCLUDE_MACOS:
        print("  [+] macOS 平台已包含")
    else:
        print("  [-] macOS 平台已排除")
    
    print("\n[可选模块]")
    
    # 如果不需要 UI 模块，删除
    if not INCLUDE_UI:
        remove_directory(f"Sources/{PACKAGE_NAME}/UI")
        remove_file(f"Tests/{PACKAGE_NAME}Tests/UITests.swift")
        print("  [-] SwiftUI 组件已排除")
    else:
        print("  [+] SwiftUI 组件已包含")
        print("  [+] SwiftUI UI 测试已包含 (XCTest)")
    
    print("\n[完成] Package 生成成功\n")
    print("后续步骤:")
    print(f"  1. cd {PACKAGE_NAME}")
    print("  2. swift build")
    print("  3. swift test")
    print("\n使用方式:")
    print("  远程 Git: .package(url: \"https://github.com/user/" + PACKAGE_NAME + ".git\", from: \"1.0.0\")")
    print("  本地路径: .package(path: \"../" + PACKAGE_NAME + "\")")


if __name__ == "__main__":
    main()

