#!/usr/bin/env python3
# Generated by Cursor
"""
Cookiecutter 模板后处理钩子。
处理平台选择、可选模块，并通过 XcodeGen 生成 Xcode 项目。
"""

import os
import re
import shutil
import subprocess

PROJECT_DIR = os.path.realpath(os.path.curdir)
PROJECT_NAME = "{{ cookiecutter.project_name }}"

# 配置标志
PLATFORMS = "{{ cookiecutter.platforms }}"
INCLUDE_NETWORK = "{{ cookiecutter.include_network }}" == "yes"
INCLUDE_PERSISTENCE = "{{ cookiecutter.include_persistence }}" == "yes"
INCLUDE_ICLOUD = "{{ cookiecutter.include_icloud }}" == "yes"

# 平台标志
INCLUDE_IOS = PLATFORMS in ["iOS", "iOS and macOS"]
INCLUDE_MACOS = PLATFORMS in ["macOS", "iOS and macOS"]


def remove_directory(path: str) -> None:
    """删除目录（如果存在）。"""
    full_path = os.path.join(PROJECT_DIR, path)
    if os.path.exists(full_path):
        shutil.rmtree(full_path)
        print(f"  已删除: {path}")


def remove_file(path: str) -> None:
    """删除文件（如果存在）。"""
    full_path = os.path.join(PROJECT_DIR, path)
    if os.path.exists(full_path):
        os.remove(full_path)
        print(f"  已删除: {path}")


def remove_yaml_section(content: str, section_pattern: str) -> str:
    """删除匹配模式的 YAML 段落。"""
    pattern = rf'(\n  # {section_pattern}.*?(?=\n  # |\n  "[^"]+":|\nschemes:|\Z))'
    return re.sub(pattern, '', content, flags=re.DOTALL)


def remove_yaml_target(content: str, target_name: str) -> str:
    """从 project.yml 删除目标段落。"""
    pattern = rf'\n  "{re.escape(target_name)}":\n    type:.*?(?=\n  "|$)'
    content = re.sub(pattern, '', content, flags=re.DOTALL)
    return content


def remove_yaml_scheme(content: str, scheme_name: str) -> str:
    """从 project.yml 删除 scheme 段落。"""
    pattern = rf'\n  "{re.escape(scheme_name)}":\n    build:.*?(?=\n  "|$)'
    content = re.sub(pattern, '', content, flags=re.DOTALL)
    return content


def process_project_yml() -> None:
    """处理 project.yml，配置平台和 iCloud。"""
    project_yml_path = os.path.join(PROJECT_DIR, "project.yml")
    
    with open(project_yml_path, "r") as f:
        content = f.read()
    
    # 如果不需要 iOS，删除 iOS 目标
    if not INCLUDE_IOS:
        content = remove_yaml_section(content, "iOS Target")
        content = remove_yaml_section(content, "iOS Tests")
        content = remove_yaml_scheme(content, f"{PROJECT_NAME}")
        content = re.sub(r'\n    iOS: "[^"]+"', '', content)
        print("  [-] iOS 平台已排除")
    else:
        print("  [+] iOS 平台已包含 (iPhone + iPad)")
    
    # 如果不需要 macOS，删除 macOS 目标
    if not INCLUDE_MACOS:
        content = remove_yaml_section(content, "macOS Target")
        content = remove_yaml_section(content, "macOS Tests")
        content = remove_yaml_scheme(content, f"{PROJECT_NAME}-macOS")
        content = re.sub(r'\n    macOS: "[^"]+"', '', content)
        print("  [-] macOS 平台已排除")
    else:
        print("  [+] macOS 平台已包含")
    
    # 如果启用 iCloud，添加 entitlements 配置
    if INCLUDE_ICLOUD and INCLUDE_PERSISTENCE:
        entitlements_line = f'        CODE_SIGN_ENTITLEMENTS: "{PROJECT_NAME}/{PROJECT_NAME}.entitlements"'
        content = content.replace(
            "        ENABLE_PREVIEWS: YES\n        TARGETED_DEVICE_FAMILY:",
            f"        ENABLE_PREVIEWS: YES\n{entitlements_line}\n        TARGETED_DEVICE_FAMILY:"
        )
        if INCLUDE_MACOS:
            content = content.replace(
                "        ENABLE_HARDENED_RUNTIME: YES",
                f"        ENABLE_HARDENED_RUNTIME: YES\n{entitlements_line}"
            )
    
    # 清理多余空行
    content = re.sub(r'\n{3,}', '\n\n', content)
    
    with open(project_yml_path, "w") as f:
        f.write(content)


def run_xcodegen() -> bool:
    """运行 XcodeGen 生成 Xcode 项目。"""
    print("\n> 正在使用 XcodeGen 生成 Xcode 项目...")
    
    try:
        subprocess.run(["xcodegen", "--version"], check=True, capture_output=True)
    except FileNotFoundError:
        print("\n[警告] 未找到 XcodeGen，请执行:")
        print("   brew install xcodegen")
        print(f"\n然后执行: cd {PROJECT_DIR} && xcodegen generate")
        return False
    except subprocess.CalledProcessError:
        return False
    
    try:
        result = subprocess.run(
            ["xcodegen", "generate"],
            cwd=PROJECT_DIR,
            check=True,
            capture_output=True,
            text=True,
        )
        print(result.stdout)
        return True
    except subprocess.CalledProcessError as e:
        print(f"\n[错误] XcodeGen 失败: {e.stderr}")
        return False


def main() -> None:
    """主入口。"""
    print("\n> 处理项目配置...\n")
    print("[平台]")
    
    # 处理平台配置
    process_project_yml()
    
    # 如果不需要 macOS，删除相关文件
    if not INCLUDE_MACOS:
        remove_file(f"{PROJECT_NAME}/Info-macOS.plist")
        remove_directory(f"{PROJECT_NAME}/Presentation/Scenes/macOS")
    
    print("\n[可选模块]")
    
    # 如果不需要网络模块，删除
    if not INCLUDE_NETWORK:
        remove_directory(f"{PROJECT_NAME}/Data/Network")
        print("  [-] 网络模块已排除")
    else:
        print("  [+] 网络模块已包含")

    # 如果不需要持久化模块，删除
    if not INCLUDE_PERSISTENCE:
        remove_directory(f"{PROJECT_NAME}/Data/Persistence")
        print("  [-] 持久化模块已排除")
    else:
        print("  [+] 持久化模块已包含")

    # 处理 iCloud
    if INCLUDE_ICLOUD and INCLUDE_PERSISTENCE:
        print("      iCloud/CloudKit 已启用")
    else:
        remove_file(f"{PROJECT_NAME}/{PROJECT_NAME}.entitlements")
        if INCLUDE_ICLOUD and not INCLUDE_PERSISTENCE:
            print("  [警告] iCloud 需要持久化模块，已禁用 iCloud")

    # 生成 Xcode 项目
    xcodegen_success = run_xcodegen()

    print("\n[完成] 项目生成成功\n")
    print("后续步骤:")
    if not xcodegen_success:
        print("  1. 安装 XcodeGen: brew install xcodegen")
        print(f"  2. cd {PROJECT_NAME}")
        print("  3. xcodegen generate")
        print(f"  4. 打开 {PROJECT_NAME}.xcodeproj")
    else:
        print(f"  1. cd {PROJECT_NAME}")
        print(f"  2. 打开 {PROJECT_NAME}.xcodeproj")
    print("  3. 构建并运行")


if __name__ == "__main__":
    main()
