// Generated by Cursor
import Foundation

// MARK: - Repository Protocol

/// Repository protocol defines the contract for data access.
/// Implementation details are hidden in the Data layer.
protocol ExampleRepositoryProtocol: Sendable {
    func fetchAll() async throws -> [ExampleEntity]
    func fetch(by id: String) async throws -> ExampleEntity?
    func save(_ entity: ExampleEntity) async throws
    func delete(by id: String) async throws
}

// MARK: - Repository Error

enum RepositoryError: LocalizedError {
    case notFound
    case saveFailed
    case deleteFailed
    case networkError(Error)
    case persistenceError(Error)
    
    var errorDescription: String? {
        switch self {
        case .notFound:
            return "Resource not found"
        case .saveFailed:
            return "Failed to save resource"
        case .deleteFailed:
            return "Failed to delete resource"
        case .networkError(let error):
            return "Network error: \(error.localizedDescription)"
        case .persistenceError(let error):
            return "Persistence error: \(error.localizedDescription)"
        }
    }
}

