// Generated by Cursor
import SwiftUI
import Factory

#if os(macOS)
struct MacContentView: View {
    @State private var selectedItem: String?
    @State private var viewModel: HomeViewModel
    
    init() {
        _viewModel = State(initialValue: Container.shared.homeViewModel())
    }
    
    var body: some View {
        NavigationSplitView {
            SidebarView(
                items: viewModel.items,
                selectedItem: $selectedItem,
                isLoading: viewModel.isLoading
            )
        } detail: {
            DetailPaneView(selectedItem: selectedItem)
        }
        .task {
            await viewModel.loadItems()
        }
    }
}

// MARK: - Sidebar View

struct SidebarView: View {
    let items: [String]
    @Binding var selectedItem: String?
    let isLoading: Bool
    
    var body: some View {
        Group {
            if isLoading {
                ProgressView("Loading...")
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
            } else {
                List(items, id: \.self, selection: $selectedItem) { item in
                    Label(item, systemImage: "doc")
                }
            }
        }
        .navigationSplitViewColumnWidth(min: 200, ideal: 250)
        .toolbar {
            ToolbarItem {
                Button {
                    // Add action
                } label: {
                    Label("Add Item", systemImage: "plus")
                }
            }
        }
    }
}

// MARK: - Detail Pane View

struct DetailPaneView: View {
    let selectedItem: String?
    
    var body: some View {
        if let item = selectedItem {
            VStack(spacing: 20) {
                Image(systemName: "doc.text.magnifyingglass")
                    .font(.system(size: 60))
                    .foregroundStyle(.secondary)
                
                Text("Detail View")
                    .font(.largeTitle)
                
                Text("Selected: \(item)")
                    .font(.title3)
                    .foregroundStyle(.secondary)
                
                Divider()
                    .padding(.horizontal, 40)
                
                Text("This is the detail view for the macOS platform.")
                    .foregroundStyle(.secondary)
            }
            .frame(maxWidth: .infinity, maxHeight: .infinity)
            .background(.background)
        } else {
            ContentUnavailableView(
                "No Selection",
                systemImage: "sidebar.left",
                description: Text("Select an item from the sidebar")
            )
        }
    }
}

// MARK: - Settings Window (macOS)

struct MacSettingsView: View {
    var body: some View {
        TabView {
            GeneralSettingsView()
                .tabItem {
                    Label("General", systemImage: "gear")
                }
            
            AppearanceSettingsView()
                .tabItem {
                    Label("Appearance", systemImage: "paintbrush")
                }
        }
        .frame(width: 450, height: 250)
    }
}

struct GeneralSettingsView: View {
    var body: some View {
        Form {
            Toggle("Enable notifications", isOn: .constant(true))
            Toggle("Auto-save", isOn: .constant(true))
        }
        .padding()
    }
}

struct AppearanceSettingsView: View {
    var body: some View {
        Form {
            Picker("Theme", selection: .constant(0)) {
                Text("System").tag(0)
                Text("Light").tag(1)
                Text("Dark").tag(2)
            }
        }
        .padding()
    }
}

#Preview {
    MacContentView()
}
#endif
