// swift-tools-version: 5.10
// Generated by Cursor
import PackageDescription

let package = Package(
    name: "{{cookiecutter.project_name}}",
    platforms: [
        .macOS(.v{{cookiecutter.macos_deployment_target | replace(".", "_") | replace("_0", "")}})
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-argument-parser.git", from: "1.5.0")
    ],
    targets: [
        .executableTarget(
            name: "{{cookiecutter.project_name}}",
            dependencies: [
                .product(name: "ArgumentParser", package: "swift-argument-parser")
            ],
            path: "Sources"
        ),
        .testTarget(
            name: "{{cookiecutter.project_name}}Tests",
            dependencies: ["{{cookiecutter.project_name}}"],
            path: "Tests"
        )
    ]
)

