#!/usr/bin/env python3
# Generated by Cursor
"""
Cookiecutter 模板后处理钩子。
根据用户选项删除不需要的模块和配置。
"""

import os
import shutil

PROJECT_DIR = os.path.realpath(os.path.curdir)
PROJECT_NAME = "{{ cookiecutter.project_name }}"
PROJECT_SLUG = "{{ cookiecutter.project_slug }}"

# 配置标志
USE_FASTAPI = "{{ cookiecutter.use_fastapi }}" == "yes"
USE_REACT = "{{ cookiecutter.use_react }}" == "yes"
USE_LANGCHAIN = "{{ cookiecutter.use_langchain }}" == "yes"
PROJECT_STRUCTURE = "{{ cookiecutter.project_structure }}"


def remove_file(path: str) -> None:
    """删除文件（如果存在）。"""
    full_path = os.path.join(PROJECT_DIR, path)
    if os.path.exists(full_path):
        os.remove(full_path)
        print(f"  已删除: {path}")


def remove_directory(path: str) -> None:
    """删除目录（如果存在）。"""
    full_path = os.path.join(PROJECT_DIR, path)
    if os.path.exists(full_path):
        shutil.rmtree(full_path)
        print(f"  已删除: {path}")


def cleanup_optional_modules() -> None:
    """删除不需要的可选模块。"""
    
    print("\n[可选模块清理]")
    
    # FastAPI 模块
    if not USE_FASTAPI:
        remove_directory(f"src/{PROJECT_SLUG}/api")
        remove_file(f"src/{PROJECT_SLUG}/model/sse_message.py")
        # 如果 model 目录为空，删除它
        model_dir = os.path.join(PROJECT_DIR, f"src/{PROJECT_SLUG}/model")
        if os.path.exists(model_dir) and not os.listdir(model_dir):
            remove_directory(f"src/{PROJECT_SLUG}/model")
        print("  [-] FastAPI 模块已排除")
    else:
        print("  [+] FastAPI 模块已包含")
    
    # React 前端
    if not USE_REACT:
        remove_directory("frontend")
        print("  [-] React 前端已排除")
    else:
        print("  [+] React 前端已包含")
    
    # LangChain 模块
    if not USE_LANGCHAIN:
        remove_directory(f"src/{PROJECT_SLUG}/executor")
        remove_file(f"src/{PROJECT_SLUG}/utils/parallel_tools_async.py")
        print("  [-] LangChain 模块已排除")
    else:
        print("  [+] LangChain 模块已包含")
    
    # 分层架构
    if PROJECT_STRUCTURE == "flat":
        remove_directory(f"src/{PROJECT_SLUG}/domain")
        remove_directory(f"src/{PROJECT_SLUG}/infra")
        print("  [-] 分层架构已排除 (使用扁平结构)")
    else:
        print("  [+] 分层架构已包含")


def update_main_py() -> None:
    """更新 main.py，移除不需要的导入。"""
    main_path = os.path.join(PROJECT_DIR, f"src/{PROJECT_SLUG}/main.py")
    
    if not os.path.exists(main_path):
        return
    
    with open(main_path, "r") as f:
        content = f.read()
    
    # 如果未启用 FastAPI，移除相关导入和路由注册
    if not USE_FASTAPI:
        # 移除 FastAPI 相关导入
        lines = content.split("\n")
        new_lines = []
        skip_next = False
        for i, line in enumerate(lines):
            if "from fastapi" in line or "import FastAPI" in line:
                skip_next = True
                continue
            if skip_next and ("from .api.routes" in line or "app.include_router" in line):
                continue
            if skip_next and line.strip() == "":
                skip_next = False
                continue
            skip_next = False
            new_lines.append(line)
        content = "\n".join(new_lines)
    
    with open(main_path, "w") as f:
        f.write(content)


def update_pyproject_toml() -> None:
    """更新 pyproject.toml，移除不需要的依赖。"""
    pyproject_path = os.path.join(PROJECT_DIR, "pyproject.toml")
    
    if not os.path.exists(pyproject_path):
        return
    
    with open(pyproject_path, "r") as f:
        content = f.read()
    
    # 移除条件依赖（如果未启用）
    lines = content.split("\n")
    new_lines = []
    skip_until_next_section = False
    
    for i, line in enumerate(lines):
        # 检查是否需要跳过 FastAPI 依赖
        if not USE_FASTAPI and ("fastapi" in line.lower() or "uvicorn" in line.lower() or "httpx" in line.lower()):
            continue
        
        # 检查是否需要跳过 LangChain 依赖
        if not USE_LANGCHAIN and ("langchain" in line.lower()):
            continue
        
        new_lines.append(line)
    
    content = "\n".join(new_lines)
    
    with open(pyproject_path, "w") as f:
        f.write(content)


def cleanup_empty_directories() -> None:
    """清理空目录。"""
    def is_empty_dir(path: str) -> bool:
        if not os.path.isdir(path):
            return False
        return len(os.listdir(path)) == 0
    
    # 递归查找并删除空目录
    for root, dirs, files in os.walk(PROJECT_DIR, topdown=False):
        # 跳过 .venv, .git 等目录
        if any(skip in root for skip in [".venv", ".git", "__pycache__", "node_modules"]):
            continue
        
        for dir_name in dirs:
            dir_path = os.path.join(root, dir_name)
            if is_empty_dir(dir_path):
                try:
                    os.rmdir(dir_path)
                    print(f"  已删除空目录: {os.path.relpath(dir_path, PROJECT_DIR)}")
                except OSError:
                    pass


def main() -> None:
    """主入口。"""
    print("\n> 处理项目配置...\n")
    
    # 清理可选模块
    cleanup_optional_modules()
    
    # 更新配置文件
    print("\n[配置更新]")
    update_main_py()
    print("  main.py 已更新")
    
    update_pyproject_toml()
    print("  pyproject.toml 已更新")
    
    # 清理空目录
    print("\n[清理空目录]")
    cleanup_empty_directories()
    
    print("\n[完成] 项目生成成功\n")
    print("后续步骤:")
    print(f"  1. cd {PROJECT_NAME}")
    print("  2. ./scripts/init_env.sh")
    print("  3. ./scripts/dev.sh")
    print("\n提示: 编辑 .env 文件配置环境变量")


if __name__ == "__main__":
    main()
