// Generated by Cursor
import SwiftUI

/// Root content view that adapts to each platform
struct ContentView: View {
    var body: some View {
        #if os(iOS)
        AppCoordinatorView()
        #elseif os(macOS)
        MacContentView()
        #endif
    }
}

#Preview {
    ContentView()
}

