#!/usr/bin/env python3
# Generated by Cursor
"""
交互式 CLI 工具，用于从 cookiecutter 模板创建 Tauri + Svelte 项目。

用法:
    python create_project.py                    # 交互模式
    python create_project.py --name my-app      # 带参数模式
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path
from typing import Optional, Union

try:
    import questionary
    from questionary import Style
    from rich.console import Console
    from rich.panel import Panel
    from rich.text import Text
    from cookiecutter.main import cookiecutter
except ImportError:
    print("缺少依赖。请执行: pip install -r requirements.txt")
    sys.exit(1)


console = Console()

# 自定义 questionary 样式：高亮背景显示选中项
CUSTOM_STYLE = Style([
    ("qmark", "fg:cyan bold"),             # 问号
    ("question", "bold"),                  # 问题文本
    ("answer", "fg:cyan bold"),            # 已回答的值
    ("pointer", "fg:black bg:cyan bold"),  # 指针（与高亮一致）
    ("highlighted", "fg:black bg:cyan"),   # 高亮选中项
    ("selected", "fg:cyan"),               # 已选择的复选框项
    ("text", ""),                          # 普通文本
    ("instruction", "fg:gray"),            # 指令提示
])

# 模板目录 (cli 文件夹的父目录)
TEMPLATE_DIR = Path(__file__).parent.parent.absolute()

# 语言选项
LOCALE_CHOICES = ["en", "zh"]


def print_banner() -> None:
    """打印欢迎横幅。"""
    banner = Text()
    banner.append("Tauri + Svelte 项目生成器\n", style="bold cyan")
    banner.append("Tauri 2.0 + Svelte 5 (Runes)\n", style="dim")
    banner.append("跨平台桌面应用模板", style="dim italic")
    console.print(Panel(banner, border_style="cyan"))


def select_folder_with_finder() -> Optional[str]:
    """使用 Finder 选择文件夹 (仅 macOS)。"""
    try:
        script = '''
        tell application "Finder"
            activate
        end tell
        set selectedFolder to choose folder with prompt "选择项目输出目录"
        return POSIX path of selectedFolder
        '''
        result = subprocess.run(
            ["osascript", "-e", script],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            return result.stdout.strip()
        return None
    except Exception:
        return None


def validate_project_name(name: str) -> Union[bool, str]:
    """验证项目名称 (kebab-case)。"""
    if not name:
        return "项目名称不能为空"
    if not name[0].isalpha():
        return "项目名称必须以字母开头"
    if not all(c.isalnum() or c == "-" for c in name):
        return "项目名称只能包含字母、数字和连字符 (kebab-case)"
    if name != name.lower():
        return "项目名称必须小写"
    return True


def interactive_prompt() -> tuple:
    """运行交互式提示，收集项目配置。返回 (config_dict, output_dir)。"""
    console.print("\n[bold]项目配置[/bold]\n")

    # 项目名称
    project_name = questionary.text(
        "项目名称 (kebab-case):",
        default="my-tauri-app",
        validate=validate_project_name,
    ).ask()
    if not project_name:
        sys.exit(0)

    # 项目描述
    project_description = questionary.text(
        "项目描述:",
        default="A Tauri desktop application",
    ).ask()
    if not project_description:
        sys.exit(0)

    # 作者名称
    author_name = questionary.text(
        "作者/组织名称:",
        default="Developer",
    ).ask()
    if not author_name:
        sys.exit(0)

    console.print("\n[bold]可选模块[/bold]\n")

    # TailwindCSS
    include_tailwind = questionary.confirm(
        "包含 TailwindCSS?",
        default=True,
    ).ask()
    if include_tailwind is None:
        sys.exit(0)

    # 国际化
    include_i18n = questionary.confirm(
        "包含国际化 (i18n)?",
        default=False,
    ).ask()
    if include_i18n is None:
        sys.exit(0)

    # 默认语言 (仅在启用 i18n 时询问，English 在前作为默认)
    default_locale = "en"
    if include_i18n:
        default_locale = questionary.select(
            "默认语言:",
            choices=[
                questionary.Choice("English", value="en"),
                questionary.Choice("中文", value="zh"),
            ],
            style=CUSTOM_STYLE,
        ).ask()
        if not default_locale:
            sys.exit(0)

    console.print("\n[bold]Tauri 功能[/bold]\n")

    # 系统托盘
    include_tray = questionary.confirm(
        "包含系统托盘?",
        default=False,
    ).ask()
    if include_tray is None:
        sys.exit(0)

    # 自动更新
    include_updater = questionary.confirm(
        "包含自动更新功能?",
        default=False,
    ).ask()
    if include_updater is None:
        sys.exit(0)

    # 文件系统 API
    include_fs = questionary.confirm(
        "包含文件系统 API?",
        default=False,
    ).ask()
    if include_fs is None:
        sys.exit(0)

    # Python 后端
    include_python = questionary.confirm(
        "包含 Python 后端支持?",
        default=False,
    ).ask()
    if include_python is None:
        sys.exit(0)

    # Python 解释器 (仅在启用 Python 时询问，RustPython 在前作为默认)
    python_interpreter = "rustpython"
    if include_python:
        python_interpreter = questionary.select(
            "Python 解释器:",
            choices=[
                questionary.Choice("RustPython (静态链接，部署简单)", value="rustpython"),
                questionary.Choice("PyO3 (需要系统 Python，支持更多库)", value="pyo3"),
            ],
            style=CUSTOM_STYLE,
        ).ask()
        if not python_interpreter:
            sys.exit(0)

    console.print("\n[bold]输出位置[/bold]\n")

    # 输出目录选择（当前目录在前作为默认）
    output_dir = None
    output_choice = questionary.select(
        "项目输出目录:",
        choices=[
            questionary.Choice(f"当前目录 ({os.getcwd()})", value="cwd"),
            questionary.Choice("通过 Finder 选择...", value="finder"),
            questionary.Choice("手动输入路径", value="manual"),
        ],
        style=CUSTOM_STYLE,
    ).ask()
    if not output_choice:
        sys.exit(0)

    if output_choice == "finder":
        console.print("[dim]正在打开 Finder...[/dim]")
        output_dir = select_folder_with_finder()
        if output_dir:
            console.print(f"[green]已选择:[/green] {output_dir}")
        else:
            console.print("[yellow]未选择目录，使用当前目录[/yellow]")
            output_dir = os.getcwd()
    elif output_choice == "manual":
        output_dir = questionary.path(
            "输入目录路径:",
            default=os.getcwd(),
            only_directories=True,
        ).ask()
        if not output_dir:
            output_dir = os.getcwd()
    else:
        output_dir = os.getcwd()

    config = {
        "project_name": project_name,
        "project_description": project_description,
        "author_name": author_name,
        "include_tailwind": "yes" if include_tailwind else "no",
        "include_i18n": "yes" if include_i18n else "no",
        "include_tray": "yes" if include_tray else "no",
        "include_updater": "yes" if include_updater else "no",
        "include_fs": "yes" if include_fs else "no",
        "include_python": "yes" if include_python else "no",
        "python_interpreter": python_interpreter,
        "default_locale": default_locale,
    }

    return config, output_dir


def create_project(
    output_dir: Optional[str] = None,
    extra_context: Optional[dict] = None,
    no_input: bool = False,
) -> str:
    """从模板创建项目。"""
    output_dir = output_dir or os.getcwd()

    result = cookiecutter(
        str(TEMPLATE_DIR),
        output_dir=output_dir,
        extra_context=extra_context,
        no_input=no_input,
    )

    return result


def main() -> None:
    """主入口。"""
    parser = argparse.ArgumentParser(
        description="从模板创建 Tauri + Svelte 项目"
    )
    parser.add_argument(
        "--name",
        "-n",
        help="项目名称 (kebab-case)",
    )
    parser.add_argument(
        "--description",
        "-d",
        help="项目描述",
    )
    parser.add_argument(
        "--author",
        "-a",
        help="作者/组织名称",
    )
    parser.add_argument(
        "--output-dir",
        "-o",
        help="输出目录 (默认: 当前目录)",
    )
    parser.add_argument(
        "--no-tailwind",
        action="store_true",
        help="排除 TailwindCSS",
    )
    parser.add_argument(
        "--i18n",
        action="store_true",
        help="包含国际化模块",
    )
    parser.add_argument(
        "--locale",
        choices=LOCALE_CHOICES,
        default="en",
        help="默认语言 (默认: en)",
    )
    parser.add_argument(
        "--tray",
        action="store_true",
        help="包含系统托盘",
    )
    parser.add_argument(
        "--updater",
        action="store_true",
        help="包含自动更新",
    )
    parser.add_argument(
        "--fs",
        action="store_true",
        help="包含文件系统 API",
    )
    parser.add_argument(
        "--python",
        action="store_true",
        help="包含 Python 后端支持",
    )
    parser.add_argument(
        "--python-interpreter",
        choices=["rustpython", "pyo3"],
        default="rustpython",
        help="Python 解释器 (默认: rustpython)",
    )
    parser.add_argument(
        "--non-interactive",
        action="store_true",
        help="非交互模式运行 (需要 --name)",
    )

    args = parser.parse_args()

    print_banner()

    if args.non_interactive:
        if not args.name:
            console.print("[red]错误: 非交互模式需要 --name 参数[/red]")
            sys.exit(1)

        extra_context = {
            "project_name": args.name,
            "project_description": args.description or "A Tauri desktop application",
            "author_name": args.author or "Developer",
            "include_tailwind": "no" if args.no_tailwind else "yes",
            "include_i18n": "yes" if args.i18n else "no",
            "include_tray": "yes" if args.tray else "no",
            "include_updater": "yes" if args.updater else "no",
            "include_fs": "yes" if args.fs else "no",
            "include_python": "yes" if args.python else "no",
            "python_interpreter": args.python_interpreter,
            "default_locale": args.locale,
        }
        output_dir = args.output_dir
    else:
        extra_context, output_dir = interactive_prompt()
        # 命令行参数优先级高于交互式选择
        if args.output_dir:
            output_dir = args.output_dir

    console.print("\n[bold]正在生成项目...[/bold]\n")

    # 预计的项目路径，用于失败时清理
    output_dir = output_dir or os.getcwd()
    expected_path = os.path.join(output_dir, extra_context["project_name"])

    try:
        project_path = create_project(
            output_dir=output_dir,
            extra_context=extra_context,
            no_input=True,
        )
        console.print(f"\n[green]项目创建成功:[/green] {project_path}")
    except Exception as e:
        import shutil
        import traceback
        console.print(f"\n[red]创建项目失败:[/red] {e}")
        console.print("\n[dim]堆栈跟踪:[/dim]")
        console.print(traceback.format_exc())
        # 清理失败的项目目录
        if os.path.exists(expected_path):
            shutil.rmtree(expected_path)
            console.print(f"\n[yellow]已清理:[/yellow] {expected_path}")
        sys.exit(1)


if __name__ == "__main__":
    main()

