// Generated by Cursor
import SwiftUI
import Factory

#if os(iOS)
struct HomeView: View {
    @State private var viewModel: HomeViewModel
    @Environment(AppCoordinator.self) private var coordinator
    
    init() {
        _viewModel = State(initialValue: Container.shared.homeViewModel())
    }
    
    var body: some View {
        Group {
            if viewModel.isLoading {
                ProgressView("Loading...")
            } else {
                List {
                    ForEach(viewModel.items, id: \.self) { item in
                        Button {
                            coordinator.push(.detail(id: item))
                        } label: {
                            HStack {
                                Image(systemName: "doc")
                                    .foregroundStyle(.blue)
                                Text(item)
                                Spacer()
                                Image(systemName: "chevron.right")
                                    .foregroundStyle(.secondary)
                            }
                        }
                        .foregroundStyle(.primary)
                    }
                }
            }
        }
        .navigationTitle("{{cookiecutter.project_name}}")
        .toolbar {
            ToolbarItem(placement: .topBarTrailing) {
                Button {
                    coordinator.present(.settings, as: .sheet)
                } label: {
                    Image(systemName: "gear")
                }
            }
        }
        .task {
            await viewModel.loadItems()
        }
    }
}

#Preview {
    NavigationStack {
        HomeView()
    }
    .environment(AppCoordinator())
}
#endif
