"""Generated by Cursor
配置加载模块，用于从环境变量加载配置
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import multiprocessing

# 环境变量前缀映射
ENV_PREFIXES = {
    "env.app": "APP_",
{%- if cookiecutter.use_langchain == "yes" %}
    "env.chat": "CHAT_",
    "env.embed": "EMBED_"
{%- endif %}
}

# 加载环境变量
def load_env_files() -> None:
    """
    加载所有环境变量文件
    按照优先级从高到低加载：
    1. env.app
{%- if cookiecutter.use_langchain == "yes" %}
    2. env.chat
    3. env.embed
{%- endif %}
    
    每个环境变量文件中的变量会添加对应的前缀，避免覆盖问题
    """
    # 获取项目根目录
    # 确保获取到正确的项目根目录，无论从哪里调用
    root_dir = Path(__file__).resolve().parent.parent.parent.parent
    # 如果在开发环境中找不到.env文件，尝试使用当前工作目录
    if not (root_dir / "env.app").exists(){%- if cookiecutter.use_langchain == "yes" %} and not (root_dir / "env.chat").exists(){%- endif %}:
        root_dir = Path(os.getcwd())
        # 如果当前目录也没有.env文件，向上查找直到找到包含.env文件的目录
        while root_dir != root_dir.parent and not any((root_dir / f).exists() for f in ENV_PREFIXES.keys()):
            root_dir = root_dir.parent
    
    # 按优先级加载环境变量文件
    env_files = [
        root_dir / "env.app",
{%- if cookiecutter.use_langchain == "yes" %}
        root_dir / "env.chat",
        root_dir / "env.embed"
{%- endif %}
    ]
    
    for env_file in env_files:
        if env_file.exists():
            # 获取对应的前缀
            prefix = ENV_PREFIXES.get(env_file.name, "")
            
            # 使用load_dotenv加载环境变量，并设置前缀
            load_dotenv(env_file, override=False)
            
            # 为加载的环境变量添加前缀
            env_vars = dict(os.environ)
            for key, value in env_vars.items():
                # 跳过已经有前缀的变量
                if any(key.startswith(p) for p in ENV_PREFIXES.values()):
                    continue
                
                # 添加前缀
                prefixed_key = f"{prefix}{key}"
                os.environ[prefixed_key] = value

# 加载环境变量
load_env_files()

# 基础配置类
class BaseConfig:
    """基础配置类，提供通用的配置方法"""
    
    # 配置前缀
    PREFIX: str = ""
    
    @classmethod
    def get_str(cls, key: str, default: str = "") -> str:
        """获取字符串配置"""
        # 尝试带前缀的键
        prefixed_key = f"{cls.PREFIX}{key}"
        value = os.getenv(prefixed_key)
        
        # 如果带前缀的键不存在，尝试不带前缀的键（向后兼容）
        if value is None:
            value = os.getenv(key, default)
        
        return value
    
    @classmethod
    def get_int(cls, key: str, default: int = 0) -> int:
        """获取整数配置"""
        try:
            # 尝试带前缀的键
            prefixed_key = f"{cls.PREFIX}{key}"
            value = os.getenv(prefixed_key)
            
            # 如果带前缀的键不存在，尝试不带前缀的键（向后兼容）
            if value is None:
                value = os.getenv(key, str(default))
            
            return int(value)
        except (ValueError, TypeError):
            return default
    
    @classmethod
    def get_bool(cls, key: str, default: bool = False) -> bool:
        """获取布尔配置"""
        # 尝试带前缀的键
        prefixed_key = f"{cls.PREFIX}{key}"
        value = os.getenv(prefixed_key)
        
        # 如果带前缀的键不存在，尝试不带前缀的键（向后兼容）
        if value is None:
            value = os.getenv(key, str(default))
        
        value = value.lower()
        return value in ("true", "1", "t", "yes", "y")

# 服务器配置
class ServerConfig(BaseConfig):
    """服务器配置类"""
    
    # 配置前缀
    PREFIX = "APP_"
    
    # API配置
    API_VERSION: str = BaseConfig.get_str("API_VERSION", "v1")
    API_PREFIX: str = BaseConfig.get_str("API_PREFIX", f"/api/{API_VERSION}")
    
    # 服务器配置
    HOST: str = BaseConfig.get_str("HOST", "0.0.0.0")
    PORT: int = BaseConfig.get_int("PORT", 8000)
    DEBUG: bool = BaseConfig.get_bool("DEBUG", False)
    # 默认使用 CPU 核心数作为工作进程数，调试模式下使用单进程
    WORKERS: int = BaseConfig.get_int("WORKERS", 1 if DEBUG else max(1, multiprocessing.cpu_count()))
    # 日志配置
    LOG_LEVEL: str = BaseConfig.get_str("LOG_LEVEL", "INFO")
    LOG_DIR: str = BaseConfig.get_str("LOG_DIR", "logs")
    APP_NAME: str = BaseConfig.get_str("APP_NAME", "{{ cookiecutter.project_slug }}")
    
    # 路径配置（可通过环境变量覆盖，默认使用 path_config 中的值）
    WORKSPACE_DIR: str = BaseConfig.get_str("WORKSPACE_DIR", "")
    TEMP_DIR: str = BaseConfig.get_str("TEMP_DIR", "")
    OUTPUT_DIR: str = BaseConfig.get_str("OUTPUT_DIR", "")
    
    # 应用密钥配置
    APP_KEY: str = BaseConfig.get_str("APP_KEY", "")

{%- if cookiecutter.use_langchain == "yes" %}
# OpenAI聊天配置
class ChatConfig(BaseConfig):
    """OpenAI聊天配置类"""
    
    # 配置前缀
    PREFIX = "CHAT_"
    
    # API配置
    OPENAI_API_KEY: str = BaseConfig.get_str("OPENAI_API_KEY", "")
    OPENAI_API_BASE: str = BaseConfig.get_str("OPENAI_API_BASE", "https://api.openai.com/v1")
    MODEL_NAME: str = BaseConfig.get_str("MODEL_NAME", "gpt-3.5-turbo")
    REQUESTS_PER_MINUTE: int = BaseConfig.get_int("REQUESTS_PER_MINUTE", 200)
    MAX_TOKENS: int = BaseConfig.get_int("MAX_TOKENS", 2000)  # 默认2000 tokens
    MAX_WORKERS: int = BaseConfig.get_int("MAX_WORKERS", multiprocessing.cpu_count() * 2)
    TIMEOUT: int = BaseConfig.get_int("TIMEOUT", 1800)

# Embedding配置
class EmbeddingConfig(BaseConfig):
    """Embedding配置类"""
    
    # 配置前缀
    PREFIX = "EMBED_"
    
    # API配置
    OPENAI_API_KEY: str = BaseConfig.get_str("OPENAI_API_KEY", "")
    OPENAI_API_BASE: str = BaseConfig.get_str("OPENAI_API_BASE", "https://api.openai.com/v1")
    MODEL_NAME: str = BaseConfig.get_str("MODEL_NAME", "gpt-3.5-turbo")
    
    # Embedding配置
    EMBEDDING_MODEL: str = BaseConfig.get_str("EMBEDDING_MODEL", "text-embedding-3-small")
    EMBEDDING_DIMENSION: int = BaseConfig.get_int("EMBEDDING_DIMENSION", 1536)
    REQUESTS_PER_MINUTE: int = BaseConfig.get_int("REQUESTS_PER_MINUTE", 120)
    
    # 编码格式
    EMBEDDING_ENCODING_FORMAT: str = BaseConfig.get_str("EMBEDDING_ENCODING_FORMAT", "float")
    
    # 向量存储配置
    VECTOR_STORE_INDEX_TYPE: str = BaseConfig.get_str("VECTOR_STORE_INDEX_TYPE", "flat")
    DISTANCE_TYPE: str = BaseConfig.get_str("DISTANCE_TYPE", "cosine")
    
    # 并行处理配置
    MAX_WORKERS: int = BaseConfig.get_int("MAX_WORKERS", 5)
{%- endif %}

# 创建配置实例
server_config = ServerConfig()
{%- if cookiecutter.use_langchain == "yes" %}
chat_config = ChatConfig()
embedding_config = EmbeddingConfig()
{%- endif %}
