"""Generated by Cursor
路径配置模块，用于管理项目路径（workspace、temp、resources 等）
支持通过环境变量配置路径
"""

import os
from pathlib import Path
from typing import Optional


def _find_project_root(start_path: Optional[Path] = None) -> Path:
    """
    查找项目根目录
    
    查找策略（按优先级）：
    1. 环境变量 PROJECT_ROOT
    2. 从当前文件向上查找包含 pyproject.toml 的目录
    3. 从当前工作目录向上查找包含 pyproject.toml 的目录
    4. 回退到当前工作目录
    
    Args:
        start_path: 起始查找路径，默认为当前文件所在目录
        
    Returns:
        项目根目录路径
    """
    # 1. 优先使用环境变量
    env_root = os.getenv("PROJECT_ROOT")
    if env_root:
        root = Path(env_root).resolve()
        if root.exists() and root.is_dir():
            return root
    
    # 2. 从当前文件向上查找
    if start_path is None:
        start_path = Path(__file__).resolve()
    
    current = start_path.parent if start_path.is_file() else start_path
    
    # 向上查找包含 pyproject.toml 的目录
    while current != current.parent:
        if (current / "pyproject.toml").exists():
            return current
        current = current.parent
    
    # 3. 从当前工作目录向上查找
    cwd = Path.cwd()
    current = cwd
    while current != current.parent:
        if (current / "pyproject.toml").exists():
            return current
        current = current.parent
    
    # 4. 回退到当前工作目录
    return cwd


# 项目根目录
PROJECT_ROOT = _find_project_root()

# 资源目录（项目内的资源文件）
RESOURCE_DIR = PROJECT_ROOT / "src" / "resources"

def _resolve_path(env_key: str, default_relative: Path) -> Path:
    """
    解析路径配置
    
    支持环境变量（带或不带 APP_ 前缀）：
    1. APP_WORKSPACE_DIR / WORKSPACE_DIR
    2. APP_TEMP_DIR / TEMP_DIR
    3. APP_OUTPUT_DIR / OUTPUT_DIR
    
    如果是绝对路径，直接使用；否则相对于默认路径的父目录
    
    Args:
        env_key: 环境变量键名（不含前缀）
        default_relative: 默认相对路径
        
    Returns:
        解析后的路径
    """
    # 尝试带 APP_ 前缀的环境变量（与 env_config.py 一致）
    value = os.getenv(f"APP_{env_key}") or os.getenv(env_key)
    
    if value:
        path = Path(value)
        # 如果是绝对路径，直接使用
        if path.is_absolute():
            return path
        # 否则相对于默认路径的父目录（通常是 PROJECT_ROOT 或 WORKSPACE_DIR）
        return default_relative.parent / path
    
    return default_relative


# 工作区目录（可配置，默认在项目根目录下）
WORKSPACE_DIR = _resolve_path("WORKSPACE_DIR", PROJECT_ROOT / "workspace")

# 输出目录（工作区内的输出目录）
OUTPUT_DIR = _resolve_path("OUTPUT_DIR", WORKSPACE_DIR / "output")

# 临时目录（工作区内的临时文件目录）
TEMP_DIR = _resolve_path("TEMP_DIR", WORKSPACE_DIR / "temp")

# 确保必要的目录存在
for dir_path in [WORKSPACE_DIR, OUTPUT_DIR, TEMP_DIR]:
    dir_path.mkdir(parents=True, exist_ok=True)
