// Generated by Cursor
// {{cookiecutter.package_name}} - Core Logic

import Foundation

/// Example service demonstrating core functionality.
public struct ExampleService {
    public init() {}
    
    /// Greets the given name.
    /// - Parameter name: The name to greet.
    /// - Returns: A greeting message.
    public func greet(_ name: String) -> String {
        "Hello, \(name)!"
    }
    
    /// Adds two integers.
    /// - Parameters:
    ///   - a: First integer.
    ///   - b: Second integer.
    /// - Returns: Sum of a and b.
    public func add(_ a: Int, _ b: Int) -> Int {
        a + b
    }
}

