// Generated by Cursor
import SwiftUI

#if os(iOS)
// MARK: - App Route

enum AppRoute: Route {
    case home
    case detail(id: String)
    case settings
}

// MARK: - App Coordinator

@MainActor
@Observable
final class AppCoordinator: Coordinator {
    var navigationPath = NavigationPath()
    var sheet: AppRoute?
    var fullScreenCover: AppRoute?
    
    @ViewBuilder
    func view(for route: AppRoute) -> some View {
        switch route {
        case .home:
            HomeView()
        case .detail(let id):
            DetailView(id: id)
        case .settings:
            SettingsView()
        }
    }
}

// MARK: - App Coordinator View

struct AppCoordinatorView: View {
    @State private var coordinator = AppCoordinator()
    
    var body: some View {
        NavigationStack(path: $coordinator.navigationPath) {
            coordinator.view(for: .home)
                .navigationDestination(for: AppRoute.self) { route in
                    coordinator.view(for: route)
                }
        }
        .sheet(item: $coordinator.sheet) { route in
            coordinator.view(for: route)
        }
        .fullScreenCover(item: $coordinator.fullScreenCover) { route in
            coordinator.view(for: route)
        }
        .environment(coordinator)
    }
}

// MARK: - Detail View

struct DetailView: View {
    let id: String
    @Environment(AppCoordinator.self) private var coordinator
    
    var body: some View {
        VStack(spacing: 20) {
            Image(systemName: "doc.text.magnifyingglass")
                .font(.system(size: 60))
                .foregroundStyle(.secondary)
            
            Text("Detail View")
                .font(.title)
            
            Text("ID: \(id)")
                .font(.subheadline)
                .foregroundStyle(.secondary)
        }
        .navigationTitle("Detail")
        .navigationBarTitleDisplayMode(.inline)
    }
}

// MARK: - Settings View

struct SettingsView: View {
    @Environment(\.dismiss) private var dismiss
    
    var body: some View {
        NavigationStack {
            List {
                Section("General") {
                    Label("Notifications", systemImage: "bell")
                    Label("Appearance", systemImage: "paintbrush")
                    Label("Privacy", systemImage: "lock")
                }
                
                Section("About") {
                    Label("Version", systemImage: "info.circle")
                    Label("Help", systemImage: "questionmark.circle")
                }
            }
            .navigationTitle("Settings")
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button("Done") {
                        dismiss()
                    }
                }
            }
        }
    }
}
#endif
