// Generated by Cursor
import SwiftUI

#if os(iOS)
// MARK: - Route Protocol

protocol Route: Hashable, Identifiable {
    var id: String { get }
}

extension Route {
    var id: String { String(describing: self) }
}

// MARK: - Coordinator Protocol

@MainActor
protocol Coordinator: ObservableObject {
    associatedtype RouteType: Route
    associatedtype ContentView: View
    
    var navigationPath: NavigationPath { get set }
    var sheet: RouteType? { get set }
    var fullScreenCover: RouteType? { get set }
    
    func push(_ route: RouteType)
    func pop()
    func popToRoot()
    func present(_ route: RouteType, as style: PresentationStyle)
    func dismiss()
    
    @ViewBuilder
    func view(for route: RouteType) -> ContentView
}

// MARK: - Presentation Style

enum PresentationStyle {
    case sheet
    case fullScreenCover
}

// MARK: - Default Implementation

extension Coordinator {
    func push(_ route: RouteType) {
        navigationPath.append(route)
    }
    
    func pop() {
        guard !navigationPath.isEmpty else { return }
        navigationPath.removeLast()
    }
    
    func popToRoot() {
        navigationPath = NavigationPath()
    }
    
    func present(_ route: RouteType, as style: PresentationStyle) {
        switch style {
        case .sheet:
            sheet = route
        case .fullScreenCover:
            fullScreenCover = route
        }
    }
    
    func dismiss() {
        sheet = nil
        fullScreenCover = nil
    }
}
#endif
