#!/usr/bin/env python3
# Generated by Cursor
"""
交互式 CLI 工具，用于从 cookiecutter 模板创建 Swift CLI 项目。

用法:
    python create_project.py                    # 交互模式
    python create_project.py --name MyCLI       # 带参数模式
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path
from typing import Optional, Union

try:
    import questionary
    from questionary import Style
    from rich.console import Console
    from rich.panel import Panel
    from rich.text import Text
    from cookiecutter.main import cookiecutter
except ImportError:
    print("缺少依赖。请执行: pip install -r requirements.txt")
    sys.exit(1)


console = Console()

# 自定义 questionary 样式：高亮背景显示选中项
CUSTOM_STYLE = Style([
    ("qmark", "fg:cyan bold"),             # 问号
    ("question", "bold"),                  # 问题文本
    ("answer", "fg:cyan bold"),            # 已回答的值
    ("pointer", "fg:black bg:cyan bold"),  # 指针（与高亮一致）
    ("highlighted", "fg:black bg:cyan"),   # 高亮选中项
    ("selected", "fg:cyan"),               # 已选择的复选框项
    ("text", ""),                          # 普通文本
    ("instruction", "fg:gray"),            # 指令提示
])

TEMPLATE_DIR = Path(__file__).parent.parent.absolute()


def print_banner() -> None:
    """打印欢迎横幅。"""
    banner = Text()
    banner.append("Swift CLI 生成器\n", style="bold cyan")
    banner.append("macOS 命令行工具模板\n", style="dim")
    banner.append("ArgumentParser + SPM", style="dim italic")
    console.print(Panel(banner, border_style="cyan"))


def select_folder_with_finder() -> Optional[str]:
    """使用 Finder 选择文件夹 (仅 macOS)。"""
    try:
        script = '''
        tell application "Finder"
            activate
        end tell
        set selectedFolder to choose folder with prompt "选择项目输出目录"
        return POSIX path of selectedFolder
        '''
        result = subprocess.run(
            ["osascript", "-e", script],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            return result.stdout.strip()
        return None
    except Exception:
        return None


def validate_project_name(name: str) -> Union[bool, str]:
    """验证项目名称。"""
    if not name:
        return "项目名称不能为空"
    if not name[0].isalpha():
        return "项目名称必须以字母开头"
    if not all(c.isalnum() or c == "_" for c in name):
        return "项目名称只能包含字母、数字和下划线"
    return True


def interactive_prompt() -> tuple:
    """运行交互式提示，收集项目配置。返回 (config_dict, output_dir)。"""
    console.print("\n[bold]项目配置[/bold]\n")

    project_name = questionary.text(
        "项目名称:",
        default="MyCLI",
        validate=validate_project_name,
    ).ask()
    if not project_name:
        sys.exit(0)

    author_name = questionary.text(
        "作者/组织名称:",
        default="Developer",
    ).ask()
    if not author_name:
        sys.exit(0)

    description = questionary.text(
        "项目描述:",
        default="A Swift command-line tool",
    ).ask()
    if not description:
        sys.exit(0)

    macos_target = questionary.text(
        "macOS 最低部署版本:",
        default="14.0",
    ).ask()
    if not macos_target:
        sys.exit(0)

    console.print("\n[bold]输出位置[/bold]\n")

    output_dir = None
    output_choice = questionary.select(
        "项目输出目录:",
        choices=[
            questionary.Choice(f"当前目录 ({os.getcwd()})", value="cwd"),
            questionary.Choice("通过 Finder 选择...", value="finder"),
            questionary.Choice("手动输入路径", value="manual"),
        ],
        style=CUSTOM_STYLE,
    ).ask()
    if not output_choice:
        sys.exit(0)

    if output_choice == "finder":
        console.print("[dim]正在打开 Finder...[/dim]")
        output_dir = select_folder_with_finder()
        if output_dir:
            console.print(f"[green]已选择:[/green] {output_dir}")
        else:
            console.print("[yellow]未选择目录，使用当前目录[/yellow]")
            output_dir = os.getcwd()
    elif output_choice == "manual":
        output_dir = questionary.path(
            "输入目录路径:",
            default=os.getcwd(),
            only_directories=True,
        ).ask()
        if not output_dir:
            output_dir = os.getcwd()
    else:
        output_dir = os.getcwd()

    config = {
        "project_name": project_name,
        "author_name": author_name,
        "description": description,
        "macos_deployment_target": macos_target,
    }

    return config, output_dir


def create_project(
    output_dir: Optional[str] = None,
    extra_context: Optional[dict] = None,
    no_input: bool = False,
) -> str:
    """从模板创建项目。"""
    output_dir = output_dir or os.getcwd()

    result = cookiecutter(
        str(TEMPLATE_DIR),
        output_dir=output_dir,
        extra_context=extra_context,
        no_input=no_input,
    )

    return result


def main() -> None:
    """主入口。"""
    parser = argparse.ArgumentParser(
        description="从模板创建 Swift CLI 项目"
    )
    parser.add_argument(
        "--name",
        "-n",
        help="项目名称",
    )
    parser.add_argument(
        "--author",
        "-a",
        help="作者/组织名称",
    )
    parser.add_argument(
        "--description",
        "-d",
        help="项目描述",
    )
    parser.add_argument(
        "--output-dir",
        "-o",
        help="输出目录 (默认: 当前目录)",
    )
    parser.add_argument(
        "--macos-target",
        default="14.0",
        help="macOS 最低部署版本 (默认: 14.0)",
    )
    parser.add_argument(
        "--non-interactive",
        action="store_true",
        help="非交互模式运行 (需要 --name)",
    )

    args = parser.parse_args()

    print_banner()

    if args.non_interactive:
        if not args.name:
            console.print("[red]错误: 非交互模式需要 --name 参数[/red]")
            sys.exit(1)

        extra_context = {
            "project_name": args.name,
            "author_name": args.author or "Developer",
            "description": args.description or "A Swift command-line tool",
            "macos_deployment_target": args.macos_target,
        }
        output_dir = args.output_dir
    else:
        extra_context, output_dir = interactive_prompt()
        if args.output_dir:
            output_dir = args.output_dir

    console.print("\n[bold]正在生成项目...[/bold]\n")

    output_dir = output_dir or os.getcwd()
    expected_path = os.path.join(output_dir, extra_context["project_name"])

    try:
        project_path = create_project(
            output_dir=output_dir,
            extra_context=extra_context,
            no_input=True,
        )
        console.print(f"\n[green]项目创建成功:[/green] {project_path}")
    except Exception as e:
        import shutil
        console.print(f"\n[red]创建项目失败:[/red] {e}")
        if os.path.exists(expected_path):
            shutil.rmtree(expected_path)
            console.print(f"\n[yellow]已清理:[/yellow] {expected_path}")
        sys.exit(1)


if __name__ == "__main__":
    main()

