// Generated by Cursor
/**
 * Tauri 文件系统 API 封装
 */

import {
  readTextFile,
  writeTextFile,
  readDir,
  mkdir,
  remove,
  exists,
  copyFile,
  rename,
  BaseDirectory,
} from "@tauri-apps/plugin-fs";
import { open, save } from "@tauri-apps/plugin-dialog";

export { BaseDirectory };

export interface FileEntry {
  name: string;
  isDirectory: boolean;
  isFile: boolean;
  isSymlink: boolean;
}

/**
 * 读取文本文件
 */
export async function readText(
  path: string,
  baseDir?: BaseDirectory
): Promise<string> {
  return await readTextFile(path, { baseDir });
}

/**
 * 写入文本文件
 */
export async function writeText(
  path: string,
  contents: string,
  baseDir?: BaseDirectory
): Promise<void> {
  await writeTextFile(path, contents, { baseDir });
}

/**
 * 读取目录内容
 */
export async function listDir(
  path: string,
  baseDir?: BaseDirectory
): Promise<FileEntry[]> {
  const entries = await readDir(path, { baseDir });
  return entries.map((entry) => ({
    name: entry.name,
    isDirectory: entry.isDirectory,
    isFile: entry.isFile,
    isSymlink: entry.isSymlink,
  }));
}

/**
 * 创建目录
 */
export async function createDir(
  path: string,
  baseDir?: BaseDirectory,
  recursive = true
): Promise<void> {
  await mkdir(path, { baseDir, recursive });
}

/**
 * 删除文件或目录
 */
export async function removeFile(
  path: string,
  baseDir?: BaseDirectory,
  recursive = false
): Promise<void> {
  await remove(path, { baseDir, recursive });
}

/**
 * 检查文件是否存在
 */
export async function fileExists(
  path: string,
  baseDir?: BaseDirectory
): Promise<boolean> {
  return await exists(path, { baseDir });
}

/**
 * 复制文件
 */
export async function copy(
  source: string,
  destination: string,
  sourceBaseDir?: BaseDirectory,
  destBaseDir?: BaseDirectory
): Promise<void> {
  await copyFile(source, destination, {
    fromPathBaseDir: sourceBaseDir,
    toPathBaseDir: destBaseDir,
  });
}

/**
 * 重命名/移动文件
 */
export async function move(
  oldPath: string,
  newPath: string,
  oldBaseDir?: BaseDirectory,
  newBaseDir?: BaseDirectory
): Promise<void> {
  await rename(oldPath, newPath, {
    oldPathBaseDir: oldBaseDir,
    newPathBaseDir: newBaseDir,
  });
}

/**
 * 打开文件选择对话框
 */
export async function openFileDialog(options?: {
  title?: string;
  multiple?: boolean;
  directory?: boolean;
  filters?: Array<{ name: string; extensions: string[] }>;
}): Promise<string | string[] | null> {
  return await open({
    title: options?.title,
    multiple: options?.multiple,
    directory: options?.directory,
    filters: options?.filters,
  });
}

/**
 * 打开保存文件对话框
 */
export async function saveFileDialog(options?: {
  title?: string;
  defaultPath?: string;
  filters?: Array<{ name: string; extensions: string[] }>;
}): Promise<string | null> {
  return await save({
    title: options?.title,
    defaultPath: options?.defaultPath,
    filters: options?.filters,
  });
}

