// Generated by Cursor
/**
 * Tauri 自动更新模块
 */

import { check } from "@tauri-apps/plugin-updater";
import { relaunch } from "@tauri-apps/plugin-process";

export interface UpdateInfo {
  available: boolean;
  currentVersion: string;
  version?: string;
  date?: string;
  body?: string;
}

export interface UpdateProgress {
  downloaded: number;
  total: number;
}

/**
 * 检查更新
 */
export async function checkForUpdate(): Promise<UpdateInfo> {
  try {
    const update = await check();
    if (update) {
      return {
        available: true,
        currentVersion: update.currentVersion,
        version: update.version,
        date: update.date,
        body: update.body,
      };
    }
    return {
      available: false,
      currentVersion: "",
    };
  } catch (error) {
    console.error("Failed to check for updates:", error);
    return {
      available: false,
      currentVersion: "",
    };
  }
}

/**
 * 下载并安装更新
 */
export async function downloadAndInstall(
  onProgress?: (progress: UpdateProgress) => void
): Promise<boolean> {
  try {
    const update = await check();
    if (!update) return false;

    let downloaded = 0;
    let total = 0;

    await update.downloadAndInstall((event) => {
      if (event.event === "Started") {
        total = event.data.contentLength ?? 0;
      } else if (event.event === "Progress") {
        downloaded += event.data.chunkLength;
        onProgress?.({ downloaded, total });
      }
    });

    return true;
  } catch (error) {
    console.error("Failed to download update:", error);
    return false;
  }
}

/**
 * 重启应用
 */
export async function restart(): Promise<void> {
  await relaunch();
}

